### ISSUE TITLE
Constrained nonlinear fits

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/Gpufit#10]
Is it possible to incorporate constraints on the parameters into Gpufit? If so, how do other packages do it? At least parameter lower and upper bounds on parameters seem reasonable.

**Comment by ltorres6** [comment]
Has anyone found a solution for adding upper and lower bounds with the current implementation? I've forked my own and added my model according to your instructions successfully, but the data I'm trying to fit can be noisy which can affect my estimates for the initial parameters and really send the fits off course so bounding the problem would be useful.

**Comment by jkfindeisen** [comment]
Duplicate of #61
