### ISSUE TITLE
<limits> not included in info.h

### ISSUE THREAD

**Issue by stefanhofmeister** [gpufit/Gpufit#106]
Hi, 
I just tried to compile the code, and run into this error:
Gpufit-master/Gpufit/info.cpp:122:82: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  122 |     std::size_t const highest_size_t_value = std::numeric_limits< std::size_t >::max();
Googling a bit, I found that <limits> was not included in the header file. I think it would be good if you could do that, it seems that it is not included by default. Else, everything worked fine in the compilation - I will now run a few test runs.
Best regards,
    Stefan

**Comment by lukasglandorf** [comment]
Hi, I'm facing the same problem. Seems like this is caused by using gcc-11 or higher:
https://gitlab.com/wg1/jpeg-xl/-/issues/84
