### ISSUE TITLE
Format of parameter "SIGMA" / rename to WEIGHTS

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#11]
Why is sigma not the same size as data?  I don't see any reason why sigma should not be the same as it is for the call to the C API.  ?

**Comment by jkfindeisen** [comment]
Surprisingly it works. If it is supposed to have the same size and not only fit_size then there is something wrong on the C side. The code needs to be checked and the desired behavior needs to be stated clearly.

**Comment by adrianjp88** [comment]
The CUDA code is using the same sigma for all fits. If unique sigma for each fit should be used, the code needs to be changed.

**Comment by superchromix** [comment]
Is there ANY reason why sigma should be the same for all fits?

**Comment by superchromix** [comment]
The only reason is in the case of unweighted fits.  This should somehow be made as an optional parameter.  We may need to add another call to the C interface.

**Comment by adrianjp88** [comment]
The reason to implement it in that way was the assumption that all fits have to be weighted equally.

**Comment by superchromix** [comment]
For unweighted fits, we don't need the overhead of passing a huge array of 1s to the GPU.  

sigma, like user_info, can be an optional input to the C code.  we just need an additional flag to indicate that sigma is used.  there could be three possibilities - sigma is not used (unweighted), sigma is the same size as the fit size (all fits have same weight), and sigma = data size

does it make any sense for all of the fits to have the same weighting?  I can't think of a real-world scenario where this would be applicable.

**Comment by superchromix** [comment]
for that matter, what is being passed to the gpu right now?  this change would actually affect the CUDA code itself?

**Comment by adrianjp88** [comment]
sigma could be set to default values if a null pointer is passed to gpufit. For the case that the passed sigma is not null, its size should be the same as the data size. Adding a flag, would make the interface more complicated and as you mentioned, gpufit does not need the third option.

An other option is to remove sigma from the code and use user_info for weighting.

Right now, sigma passed to the GPU hast the sames size as the fit size and changing its size to the data size would affect CUDA code as follows:
- more memory needs to be allocated
- determining the maximum chunk size needs to take the size of sigma into account 
- indexing of sigma needs to be changed, while calculating Chi-square, the gradient and hessian of LSE

**Comment by jkfindeisen** [comment]
If sigma was not used (unweighted case) would using a sigma of one be a big or rather a small performance hit? Memory consumption and estimator calculating are affected.

There are only two cases: unweighted fit (no sigma or sigma equals 1), weighted fit (one sigma for every data point).

Let's change the code and then adapt to the changes in the bindings.

**Comment by superchromix** [comment]
Another question.

Right now, we are passing in sigma, assuming that this is the 1-sigma standard deviation of the measurements.

After passing these numbers in, the code is calculating the "weights", according to:

weights = 1 / sigma^2

these weights are then used in the calculation of chi squared.

It might be a more general solution to pass in the "weights" directly to GPUfit.  This wouldn't assume that we are passing the uncertainty, for example.

**Comment by jkfindeisen** [comment]
Good idea, more general is always good.

**Comment by adrianjp88** [comment]
I will remove the calculation of the weights and rename the interface argument **sigma** to **weights**. Also, no GPU memory will be allocated and no weighting will be used if **weights** is a null pointer.

**Comment by superchromix** [comment]
In the C interface, I would recommend leaving weights where it is, directly after data, even though it is optional.

**Comment by adrianjp88** [comment]
Done! The interface argument **sigma** changed to optional **weights** with unique values for each fit.

**Comment by superchromix** [comment]
please don't close until tested, and binding updated

**Comment by superchromix** [comment]
would someone please test a weighted fit?

**Comment by bjoernthiel** [comment]
updated bindings

**Comment by bjoernthiel** [comment]
we already had one - added one without weights
