### ISSUE TITLE
Optional parameters with the C interface?

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#12]
do we want to make sigma optional?  can this be done in a reasonable way?

**Comment by jkfindeisen** [comment]
It can easily be done if we would have a C++ interface. In the C interface I think this means we need to have multiple function definitions or hiding the C++ class interface (by a handle and then init, set, fit functions). So if you mean reasonable="short time" then the answer is no, if you mean longer time, then yes.

In the long run, the interface will surely evolve to something less "give me all the parameters" to "have a fit object, set some options, and go" a more object oriented/builder like approach.

**Comment by jkfindeisen** [comment]
Btw. it would be easy to have optional parameters in the external bindings (Python knows optional parameters and Matlab knows a variable number of parameters). So one question is if we need optional parameters also on the C side or only with the external bindings (lowest amount of effort for now) or if we want to evolve to a builder like interface anyway.

**Comment by adrianjp88** [comment]
I think the solution with an additional function definition would be fine.

**Comment by adrianjp88** [comment]
But in this case the interface functions must have different names. Do we want this?

**Comment by superchromix** [comment]
This issue is the same as Issue #11

**Comment by jkfindeisen** [comment]
issue #11 was a bug, this here wasn't and also I expanded it to be about more than just the sigma parameter but about all optional parameters

**Comment by jkfindeisen** [comment]
I propose to have the following parameters optional:

sigma - if not given, an unweighted fit is assumed
parameters_to_fit - if not given, all parameters are assumed to fit
user_info - if not given, no user info is passed

And the way to not give them is passing in a null pointer for the respective values in the gpufit interface function. Maybe also re-order the parameter order and put first required input parameters, then optional input parameters, then output parameters.

**Comment by adrianjp88** [comment]
I agree. Further optional parameters could be:

- tolerance - if not given, it is set to a default value
- max_n_iterations - if not given, it is set to a high default value like 100 or 1000

**Comment by jkfindeisen** [comment]
What is a reasonable default tolerance? Very small probably. I would suggest 1e-6
Reasonable max_n_iterations? 100

This would be more convenience though.

**Comment by jkfindeisen** [comment]
According to our meeting, optional parameters are

weights (null=ignored)
tolerance (0=1e-6)
max_n_iterations 0=(100)
estimator (0=LSE)
user_info (null=ignored)

In parentheses is (value indicating optionality, proposed behavior). Is this okay?

**Comment by jkfindeisen** [comment]
The current description of parameters_to_fit is: 

If value is a null pointer, hold all parameters at initial value

Does this make sense? I would assume that typically one wants to fit all parameters rather than fitting none. I mean, why calling gpufit with a default argument, that doesn't do any fitting.

If no objection, I will change this behavior to the opposite.

**Comment by superchromix** [comment]
I think the only optional parameters should be the arrays "weights" and 
"user_info".  All other parameters are required for the C interface.

Optional parameters are FINE for the bindings, but for the C interface 
they should be limited to weights and user_info.

**Comment by jkfindeisen** [comment]
Ok. That convinced me.

So, for the C-interface only weights and user_info is optional. For the external bindings more parameters are optional.

**Comment by jkfindeisen** [comment]
I adapted a test (https://github.com/gpufit/GPUfit/blob/master/tests/Gauss_Fit_1D.cpp) slightly to specify a NULL pointer as weights and user_info and it still passes. Therefore this issue can be closed.
