### ISSUE TITLE
ModuleNotFoundError: No module named 'cpufit' - Running 'make' 

### ISSUE THREAD

**Issue by jameshod5** [gpufit/Gpufit#129]
Trying to make gpufit on CentOS Linux. The error I receive is:

[  2%] Building CXX object Cpufit/CMakeFiles/Cpufit.dir/cpufit.cpp.o
[  5%] Building CXX object Cpufit/CMakeFiles/Cpufit.dir/info.cpp.o
[  8%] Building CXX object Cpufit/CMakeFiles/Cpufit.dir/lm_fit.cpp.o
[ 11%] Building CXX object Cpufit/CMakeFiles/Cpufit.dir/lm_fit_cpp.cpp.o
[ 14%] Building CXX object Cpufit/CMakeFiles/Cpufit.dir/interface.cpp.o
[ 17%] Linking CXX shared library libCpufit.so
[ 17%] Built target Cpufit
[ 17%] Built target PYTHON_PACKAGE_CPUFIT
[ 20%] Preparing Python Wheel
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    import pycpufit.version as vs
  File "/home/ir-hods1/Gpufit/Gpufit-build/pyCpufit/pycpufit/__init__.py", line 1, in <module>
    from cpufit import *
ModuleNotFoundError: No module named 'cpufit'
make[2]: *** [Cpufit/python/CMakeFiles/PYTHON_WHEEL_CPUFIT] Error 1
make[1]: *** [Cpufit/python/CMakeFiles/PYTHON_WHEEL_CPUFIT.dir/all] Error 2
make: *** [all] Error 2

Steps to reproduce have been from:

- `mkdir Gpufit`
- `cd Gpufit`
- `python -m venv venv`
- `source venv/bin/activate`
- `pip install wheel`
- `pip install Cmake`
- `git clone https://github.com/gpufit/Gpufit.git Gpufit`
- `mdkir Gpufit-build`
- `cd Gpufit-build/`
- `cmake -DCMAKE_BUILD_TYPE=RELEASE ../Gpufit`
- `make`

Running with python/3.7, CUDA/9.1 and gcc/6.

**Comment by robert-gledhill** [comment]
It looks like this is a problem with the python cpufit binding project.  I have gotten gpufit to compile by rowing back to an earlier version before the pycpufit merge:

'git reset --hard 12b3cf4f9b0bf040e06f24d71f0364cc59e8e6d7' and then following the normal cmake procedure gets it to compile for me.

**Comment by superchromix** [comment]
Hi, as mentioned, this problem was introduced in the recent commits.  We will work on fixing it.  Thanks for raising the issue.

**Comment by superchromix** [comment]
@Kubiczek36
