### ISSUE TITLE
Optional parameters with the external bindings?

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#13]
That is simple to do because Matlab and Python support these already quite well. Somebody just has to define what are the optional parameters and which default values they should have.

For example:

sigma [optional, default all 1]
parameters to fit [optional, default all true]
user_info [optional, default none]
...

**Comment by jkfindeisen** [comment]
We have now the same optional parameters with the external bindings than with the C interface. See issue #12 and this gets closed.

**Comment by jkfindeisen** [comment]
Need to reopen, because the number of optional parameters differs. 

Additionally to the optional parameters of the C Interface we have as default values if parameters aren't given.

tolerance (1e-6)
max_n_iterations (1e3)
estimator (LSE)
paramters_to_fit(all)

**Comment by superchromix** [comment]
are the bindings fully up to date now?  If I pull the latest GPUFIT, does it run from Matlab?

**Comment by superchromix** [comment]
max_n_iterations = 1000 looks like a pretty high default value.  what about 100?  or 20?

**Comment by jkfindeisen** [comment]
My rationale was that I would prefer the fits to converge and see the max_n_iterations only as insurance that the programm will actually terminate withing finite time. And since we don't know what a reasonable number of fits is for future model and estimator functions I wanted a rather high value. The default MaxIter in Matlab fminbnd is 500 for example. So what about 500?

**Comment by jkfindeisen** [comment]
"are the bindings fully up to date now? If I pull the latest GPUFIT, does it run from Matlab?"

Yesterday Python ran and Matlab crashed. I started fixing Matlab but did not finish yet. So the answer is no.

**Comment by superchromix** [comment]
OK, but the typical number of iterations in our test fits is ~5.

**Comment by superchromix** [comment]
this is a problem, since none of the tests can be run with the latest 
gpufit until the bindings are working

**Comment by jkfindeisen** [comment]
"OK, but the typical number of iterations in our test fits is ~5."

If you know that you can set the max_n_iterations to a lower value.

For other applications the typical number might be larger and there is not much sense in getting a half converged fit result, just because you could not wait a bit longer.

Not sure if 500 is optimal. We can change it at any time.

**Comment by jkfindeisen** [comment]
The bindings now use these default values. Still needs to be documented. Leave this open until it is documented.

**Comment by jkfindeisen** [comment]
Is now documented.
