### ISSUE TITLE
How does our linear solver compare to cuBLAS or cuSOLVER and should we maybe replace it?

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/Gpufit#14]
Actually I would like to know how it compares performance wise. The question would be how far away (or ahead) we are of other implementations.

See also: http://stackoverflow.com/questions/6977677/blas-lapack-routine-for-doing-gaussian-elimination
and http://docs.nvidia.com/cuda/cuda-samples/index.html#advanced

In a potential replacement we would need to take into account that cuBLAS uses dynamic parallelism (capability 3.5)??

**Comment by jkfindeisen** [comment]
A specialty is the relatively small size of the equation systems we need to solve.

**Comment by superchromix** [comment]
The solver is now using cuBLAS (LUP decomposition) on 64-bit systems.

**Comment by jkfindeisen** [comment]
I still would like to see a performance comparison. Will do this at a later time.
