### ISSUE TITLE
User info better with type void *?

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#15]
The type of user_info is currently int *.  In the linear regression example, where it is used, it contains the x-locations. Should they really be only integer precision? Is this a good idea for custom model functions in general? 

The better choice might be void * (since in general nothing is known).

**Comment by superchromix** [comment]
void * seems sensible to me

**Comment by jkfindeisen** [comment]
Yes and additionally have the user_info_size as number of user_info in bytes and by convention tell user to not provide data in a type that CUDA cannot convert (i.e. longer than 32 bit). User should convert before.

**Comment by bjoernthiel** [comment]
see #31
