### ISSUE TITLE
CUDA C interface

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/Gpufit#18]
e have a C interface, but maybe we could also use a "CUDA interface", so that if you do some stuff on the GPU before and afterwards you do not need to copy the data from and to the GPU which takes a lot of time sometimes. So basically, it would be the whole algorithm minus the data copying but already assuming the data has been copied at the beginning and doesn't need to be copied at the end.

Is this useful?

**Comment by Superzorg** [comment]
I'd say this would _definitely_ be useful.  Our use case for GpuFit requires operating on data which has already been processed on the GPU and is sitting there waiting to be fit.  Additionally, it's a large amount of data spread over 8 GPUs.  So the hit taken by transferring back to the CPU and back to the GPU inside gpufit is substantial.

**Comment by superchromix** [comment]
We have added a CUDA interface to Gpufit in the latest commits.  The function call is "gpufit_cuda_interface".  This function assumes the data to be fit, the weights, and the initial model function parameters are already present in GPU memory.

This function will be included in the upcoming release.

**Comment by jkfindeisen** [comment]
It's there since some time. Documentation is at https://gpufit.readthedocs.io/en/latest/gpufit_api.html#gpufit-cuda-interface and Example code is at https://github.com/gpufit/Gpufit/blob/master/Gpufit/examples/CUDA_Interface_Example.cu
