### ISSUE TITLE
Which performance tests do we need to include?

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#19]
Kind of like reproducing the most important figure in the paper for Gpufit.

Also for Cpufit?
Also for CMinpack? (Then we also need instructions for how to build CMinpack)

**Comment by adrianjp88** [comment]
It would be nice to compare GPUfit to C/C++ Minapck. We could show that GPUfit is much faster getting a similar fit precision.

**Comment by jkfindeisen** [comment]
See also #50

**Comment by jkfindeisen** [comment]
We decided to only supply CPUfit vs GPUfit. A comparison to CMinpack or GPLMFit may come later.
