### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/Gpufit#2]
For example with Ubuntu 16.10 (https://packages.ubuntu.com/yakkety/nvidia-cuda-toolkit)

**Comment by jkfindeisen** [comment]
And add build instructions to the documentation.

**Comment by mscipio** [comment]
In the guide you just talk about Windows ... do you think it is feasible/simple to compile the code in Linux (I have Debian or CentOS with already cuda and python up and running)?

**Comment by superchromix** [comment]
Have a look at the fork of Ingmar Rieger, here: https://github.com/irieger/Gpufit

**Comment by mscipio** [comment]
Hi!
I did and I managed to compile it and to run a couple of examples (there is something to change in the source, at least in my case, I will pull a merge request when I get everything to work)

I have 2 question now:

1) when I run the comparison tests GPUvsCPU I get a "Floating point exception" as soon as it starts to run code on the GPU. This error seems not to appear in other tests (like SimpleTest, LinearRegression, etc ...). do you think it has to do with my not-so-powerful GPU? Or maybe it is a 32/64 bit issue?

2) When I try to run the examples built with the python wrapper I got an error related to a Gpufit.dll file not found. As you commented in the code, this file is supposed to be there only on windows ... is there any way I can do something in python on Linux as well?

----------------------------------
**EDIT: I found an answer for the second issue** 
You just need to copy the compiled linux library libGpufit.so in the <src_folder>/Gpufit/python/pygpufit and change the following 2 lines of code, before running the setup.py installation:
- [**<src_folder>/Gpufit/python/setup.py # 39**] package_data={'pygpufit': ['*.so']},
- [**<src_folder>/Gpufit/python/pygpufit/gpufit.py # 16**] lib_path = os.path.join(package_dir, 'libGpufit.so') # this will only work on Linux

--> I made a pull request to the fork of Ingmar Rieger. If you want, give it a look and check if you can merge it with the main one. I didn't check the differences of the fork of Ingmar Rieger with the master, but I tried to keep my changes able to work also for the windows version.

**Comment by jkfindeisen** [comment]
I'm in the process of making Gpufit run on Linux. I copy from the forks of Ingmar Rieger and Michele Scipioni and acknowledge their contributions, but do not pull commits directly because partly they are doing other stuff that is not needed and I can test on Windows and Linux at the same time.

See 2a85a80452b8fb1a41b02f89f94aaff79a1d1da8 and before and after.

**Comment by mscipio** [comment]
If you want you can check my current pull request (without accepting it).
I just tested out your current linux-ready version on Debian and it is almost working: I needed to do just a couple of minor changes to make it compile (mostly one import in gpufit.h required by the test files).

**Comment by jkfindeisen** [comment]
Thanks, I will do this.

**Comment by jkfindeisen** [comment]
Depends on #36

**Comment by jkfindeisen** [comment]
Depends on #38

**Comment by jkfindeisen** [comment]
Since 5bf8ecf78b1f111aeecc9fd647d245fe85bd6883 the project builds on Linux and the tests as well as the performance comparison run successfully. There is documentation about the Linux build.

Still to do:

- test Python binding (should work)
- fix Matlab binding (should not work, Matlab built with different gcc version)
- packaging?

**Comment by jkfindeisen** [comment]
The project compiles and runs on Linux well but we never produced binary releases for Linux and probably never will. Therefore Linux is fully supported.
