### ISSUE TITLE
"files modified" warning after compilation

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#2]
After compiling, Visual studio gives a warning that the project files have been modified.

**Comment by bjoernthiel** [comment]
this is a Visual Studio 2013 bug / feature -- 2015 does it right

**Comment by superchromix** [comment]
reopening because this problem was not present in earlier code iterations

**Comment by jkfindeisen** [comment]
Maybe Björn can comment on the nature of the Visual Studio bug/feature and how we cause it and whether we could stop causing (which may be possible if there was a time when it wasn't present).

Otherwise I would assume we have to live with it.

**Comment by jkfindeisen** [comment]
It turns out that CMake and VisualStudio have a very complex interplay requring this behavior. Björn and Jan do not know of any possible fix to this. Therefore it should be "won't fix" for now.
