### ISSUE TITLE
Parallelization direction for Hessian matrix calculation

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/Gpufit#20]
So far the parallelization was over the number of model parameters. This is efficient for a small number of data points per fit. Now that we allow a larger number of data points per fit, this becomes inefficient. Parallelizing over the number of data points would be efficient for a large number of data points but inefficient for a small number.

The best of both world might be to parallelize over the parameters and a chunk of the data points (possibly all). Parameters could be the second block dimension and data points the first block so that the product of both does not exceed 1024.

We should test this and if beneficial include it.

**Comment by superchromix** [comment]
The parallelization of the Hessian has been changed to remove the limit on the number of model parameters.
