### ISSUE TITLE
Python and Matlab bindings for gpufit_cuda_available() function

### ISSUE THREAD

**Issue by superchromix** [gpufit/Gpufit#21]
Bindings for utility functions such as this are needed.

**Comment by jkfindeisen** [comment]
Already available in the Python bindings (https://github.com/gpufit/Gpufit/blob/master/Gpufit/python/pygpufit/gpufit.py#L196).

For Matlab it's a bit more effort. We might want to use a SWIG Matlab binding. Let's discuss this with Björn.

**Comment by jkfindeisen** [comment]
For SWIG Matlab see https://github.com/bjoernthiel/swig and https://github.com/jaeandersson/swig

**Comment by jkfindeisen** [comment]
I extended the C interface tools functions support in Python and added documentation in 28cda83cfa68ea0850c50e5a86eed612df7da601 and 820c64bc22354a50d45332f0aab3cd5f8e837642.

**Comment by superchromix** [comment]
Can we create a MEX file for gpufit_cuda_available(), at least?  Access to this function is essential for portable Matlab applications.

**Comment by jkfindeisen** [comment]
Done
