### ISSUE TITLE
Unique X coordinate values for each fit

### ISSUE THREAD

**Issue by caowencai** [gpufit/Gpufit#26]
(In a 1D Gaussian function, n_fits and  n_points_per_fit are given): to match unique X coordinate values for each fit in user_info, so the length of user_info (in type of float) is euqal to n_fits* n_points_per_fit ,the same with the length of data(the 3rd parameter in gpufit()?

**Comment by caowencai** [comment]
Have tried this: use 8 points,(x,y) to fit the model y=a*e^(b*x)+c*e^(d*x).
The result shows right when fitting  one curve 8 points each time; 
but when applying to 16 points (2 fits once, X coordinates are included in user_info), the 2nd output_parameters is  closed to the result of the first fit, which is not correct according the given input.

**Comment by adrianjp88** [comment]
The commit b897444da8792b3b2bb4101ceccc8cb0ae18143d extends the [Gauss_Fit_1D test](https://github.com/gpufit/Gpufit/blob/b897444da8792b3b2bb4101ceccc8cb0ae18143d/Gpufit/tests/Gauss_Fit_1D.cpp) to use unique x values for each fit. Please have a look at it.
