### ISSUE TITLE
Example code is broken 

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#26]
Show at least one call to the C-Interface.

Show generation of data. Improve setting of parameters...

**Comment by jkfindeisen** [comment]
The thing missing is generation of data including noise.

**Comment by adrianjp88** [comment]
generation of noised data for the gauss fit example is included now

**Comment by jkfindeisen** [comment]
I was also doing it this morning but didn't check in the code yet. :(

**Comment by adrianjp88** [comment]
sorry, I should ask you

**Comment by jkfindeisen** [comment]
I unified the examples. The Gauss 2D examples in C++/Matlab/Python are doing the same now. Need to check a bit more, then add to documentation and then this is finished.

**Comment by superchromix** [comment]
There is a bug in the example - parameters_to_fit is not initialized correctly.

Also, please randomize the initial values by adding a fraction of the true value (except for the position - here add a fraction of the width).  thanks.

**Comment by superchromix** [comment]
As far as I know, parameters_to_fit has size n_parameters.

**Comment by jkfindeisen** [comment]
You're right.

**Comment by jkfindeisen** [comment]
Example code is not broken anymore and well documented as of 589ede146fba2e894f86b047e55a54bf596c579d
