### ISSUE TITLE
Explain functional form of estimators

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#27]
Analogous to the models with a formula and explanation of the input and output arguments (data, weights, ...).

**Comment by adrianjp88** [comment]
The estimator formulas are inserted after the models.

**Comment by jkfindeisen** [comment]
I added a few sentences of explanation. I wonder, should we add functional forms of the derivatives of the estimators for the parameters or should we leave this as exercise to the reader?

**Comment by superchromix** [comment]
I think it's ok to leave this..
