### ISSUE TITLE
How many  n_fits(bytes) totally to feed once according to the GPU performance

### ISSUE THREAD

**Issue by caowencai** [gpufit/Gpufit#29]
To make a full use of the local GPU, is there any easy approach to set the proper n_fits*n_points（or in bytes) for those who are unfamiliar with cuda?
Thanks a lot.

**Comment by superchromix** [comment]
I'm not sure I understand the question.  The number of fits handled by the GPU at any one time is set automatically by the code.  The user simply passes in the total number of fits, and if this is larger than what fits on the GPU, it is automatically divided into chunks.

**Comment by caowencai** [comment]
Thanks, I get the point.
It is due to the stack memory limitation.
