### ISSUE TITLE
Compile for all compute capabilities > 2.0

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#3]
The code should, by default, compile for support of all GPUs with compute capabilities > 2.0.

**Comment by bjoernthiel** [comment]
we have CUDA_COMPUTE_CAPABILITIES CMake cache variable now to customize this

**Comment by superchromix** [comment]
This should be a flag that can be set in the cmake file.  Default should be to compile for all compute capabilities >= 2.0.

**Comment by bjoernthiel** [comment]
done
