### ISSUE TITLE
Data, weights, initial parameters in Matlab, Python are 2D arrays, no explicit size necessary

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#30]
Change API of bindings so that number_fits, number_points, number_parameters is not given explicitely but implicitely through the dimension of the input arrays (data, ...) which are assumed to be 2D arrays there.

**Comment by adrianjp88** [comment]
matlab api is changed 1b1047f1e66402db3d5a684d5497258edcd45f3d. python binding must be updated.

**Comment by jkfindeisen** [comment]
python binding also adapted in 4f2ccf2723fb1cd38af2e55cd051ea38d60862ca
