### ISSUE TITLE
Change order of parameters in the C-Interface and external interfaces

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#31]
C-Interface (n_fits, n_points, data, model_id, initial_parameters, weights, tolerance, max_n, estimator, output...)

External interfaces (data, model, initial_parameters, weights, tolerance, max_n, estimator)

**Comment by superchromix** [comment]
order and names of parameters for C interface:

size_t n_fits
size_t n_points
float32 * data
float32 * weights
int32 fit_model_ID
float32 * initial_fit_parameters
float32 fit_tolerance
int32 max_n_iterations
int32 * parameters_to_fit
int32 fit_estimator_ID
size_t user_info_size_bytes
void * user_info
float32 * output_fit_parameters
int32 * output_fit_states
float32 * output_chi_squares
int32 * output_n_iterations

**Comment by jkfindeisen** [comment]
is fit_tolerance a good name? It doesn't say which tolerance. Tolerance on fit function values? Tolerance on parameter changes? Tolerance on derivatives? 

Also the naming with prefix fit_ is inconsistent. What about fit_data, fit_weights, fit_initial_parameters...

**Comment by superchromix** [comment]
OK, we can also make it like this:

size_t n_fits
size_t n_points
float32 * data
float32 * weights
int32 model_ID
float32 * initial_fit_parameters
float32 tolerance
int32 max_n_iterations
int32 * parameters_to_fit
int32 estimator_ID
size_t user_info_size_bytes
void * user_info
float32 * output_fit_parameters
int32 * output_fit_states
float32 * output_chi_squares
int32 * output_n_iterations

**Comment by superchromix** [comment]
perhaps instead of void *, user_info should have type char *

now that we are specifying the size of user info in bytes, we are thinking of it as a block of bytes.  so, shouldn't it be a pointer to a byte array?

**Comment by superchromix** [comment]
so, the full specification would be

size_t n_fits
size_t n_points
float32 * data
float32 * weights
int32 model_ID
float32 * initial_fit_parameters
float32 tolerance
int32 max_n_iterations
int32 * parameters_to_fit
int32 estimator_ID
size_t user_info_size_bytes
char * user_info
float32 * output_fit_parameters
int32 * output_fit_states
float32 * output_chi_squares
int32 * output_n_iterations

**Comment by superchromix** [comment]
this could also be better for calls from external code such as Matlab, IDL, Labview, etc - they will have an easier time dealing with a defined type I think

**Comment by superchromix** [comment]
per the discussion with Bjorn

size_t n_fits
size_t n_points
float * data
float * weights
int model_ID
float * initial_fit_parameters
float tolerance
int max_n_iterations
int * parameters_to_fit
int estimator_ID
size_t user_info_size_bytes
char * user_info
float * output_fit_parameters
int * output_fit_states
float * output_chi_squares
int * output_n_iterations

**Comment by bjoernthiel** [comment]
left MATLAB and Python signature unchanged

**Comment by jkfindeisen** [comment]
The Matlab and Python signature is equivalent except for:

- n_fit and n_points doesn't exist but is automatically deduced from the other parameters
- output_xxx are return arguments named xxx
- the status is handled internally and an error is thrown if status is -1 including the content of get_last_error
