### ISSUE TITLE
Specify type of data, weights, ... in interface to be compatible with CUDA type restrictions

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#32]
CUDA works with int32 and float32. We don't do any conversion but expect the user to make the necessary conversions before and therefore we also specify these types now in the interface.

data, weight, initial_parameters, output_parameters, output_chi_squares -> float32 *
...

int -> int32
float -> float32

**Comment by bjoernthiel** [comment]
static assert for 32 bit int added

**Comment by jkfindeisen** [comment]
one should add that float is guaranteed to be a float32 and int was not guaranteed to be an int32 (although this is almost always the case), so asserting that int is int32 effectively solves the problem for us
