### ISSUE TITLE
change LINEAR_1D model function to OPTIONALLY user user_info

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#35]

**Comment by jkfindeisen** [comment]
In detail we said that the logic should be:

- if no user_info is given, assume equally spaced coordinates 0:1:n_points-1
- if user_info is given and user_info_size_in_bytes/4 == n_points, assume x location as float32 in user_info for each fit the same
- if user_info is given and user_info_size_in_bytes/4 == n_fits * n_points, assume x locations are float32 for every data point in user_info

**Comment by superchromix** [comment]
yes this is correct

**Comment by adrianjp88** [comment]
Now, the use of **user_info** is optionally for the **LINEAR_1D** model function.

**Comment by jkfindeisen** [comment]
this is probably still a problem with CPUfit

**Comment by adrianjp88** [comment]
fixed

**Comment by adrianjp88** [comment]
fixed
