### ISSUE TITLE
DLL not unloading cleanly

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#37]
When starting Matlab 2016 64-bit, I get the following message:

Warning: MATLAB previously crashed due to a low-level graphics error.

This occurs only when I have run GPUFIT in my previous Matlab session.  There is no error message when closing Matlab, however the next time Matlab starts, it reports this error.

**Comment by adrianjp88** [comment]
I added a command that should unload the dll after executing gpufit

**Comment by jkfindeisen** [comment]
Very strange bug. Does unloading the dll help?

**Comment by adrianjp88** [comment]
No it didn't help. I found that plotting causes the error.

**Comment by superchromix** [comment]
if we are sure that it is the plotting only, then we don't need to fix this.

**Comment by jkfindeisen** [comment]
It would be nice to have a minimal script showing the error. It may be a Matlab problem but that doesn't matter for users of GPUfit. Maybe it's a general problem and in that case sending a support request to Mathworks might be good.

**Comment by jkfindeisen** [comment]
Since commit 6073d03 didn't solve the problem I reversed it.

**Comment by adrianjp88** [comment]
The error occurs when the profiling test creating a plot is executed without calling any fitting procedure. When the test is executed calling GPUfit and CPUfit without plotting the results, no error occurs.

**Comment by jkfindeisen** [comment]
That is strange. I think I could reproduce it now with the information given, but I would still prefer a minimal script showing the error for testing and debugging.

**Comment by jkfindeisen** [comment]
I fixed the examples and it works more or less. I can have plots and do fits using GPUfit. Without a working example script I cannot recreate this bug.
