### ISSUE TITLE
Why function "configure_model" is declared in cuda_kernel.cuh and defined in mdoels.cuh?

### ISSUE THREAD

**Issue by caowencai** [gpufit/Gpufit#40]
I have built an individual vs project based on Gpufit and in my project, I have done nothing to change the code dependencies.
The function "configure_model" is declared in cuda_kernel.cuh and defined in mdoels.cuh in the src.
In my vs project, it worked well to ignore the situation, not to change header dependencies for time saving.
I guess , it is in with compiling ?

**Comment by superchromix** [comment]
This is only due to how we organize the code related to the custom model functions.
