### ISSUE TITLE
model functions need to know which chunk of fits they are processing

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#40]
this information may be needed in order to know where to access the user info.  If the user info consists of all of the X values of the fit, for example, the model function needs to know which chunk of fits it is processing, so that it can properly index the user info.

**Comment by jkfindeisen** [comment]
related to issue #39, what about letting the model decide which part of the user_info and data and weights it will need. otherwise we will make assumptions about the user_info (like it has to fit into the GPU) limiting ourselves (data and weights does not have to fit into GPU memory)

**Comment by superchromix** [comment]
The model function does decide what parts it needs, but the model 
function is not called until everything is already loaded onto the GPU. 
Hence, we need to make sure that all of user info is already there.

**Comment by jkfindeisen** [comment]
Or we need to invoke the model function earlier.  For now it's fine to load the user data.

**Comment by adrianjp88** [comment]
fixed
