### ISSUE TITLE
linear fit does not work

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#41]
the linear fit will not work properly with the user info, because it does not know which chunk of fits it is currently processing.

**Comment by adrianjp88** [comment]
fixed

**Comment by jkfindeisen** [comment]
this is probably still a problem with CPUfit

**Comment by adrianjp88** [comment]
GPUfit and CPUfit are fixed and the tests are updated

**Comment by adrianjp88** [comment]
fixed
