### ISSUE TITLE
Build errors on Ubuntu16.04

### ISSUE THREAD

**Issue by Mannix1994** [gpufit/Gpufit#42]
FLT_EPSILON was not declared in Brown_Dennis_Fit.cpp 
there are errors:
/Gpufit/Gpufit/tests/Brown_Dennis_Fit.cpp: In member function ‘void Fletcher_Powell_Helix::test_method()’:
/Gpufit/Gpufit/tests/Brown_Dennis_Fit.cpp:69:71: error: ‘FLT_EPSILON’ was not declared in this scope
     BOOST_CHECK(std::abs(output_parameters[0] - true_parameters[0]) < FLT_EPSILON);
                                                                       ^
/Gpufit/Gpufit/tests/Brown_Dennis_Fit.cpp:70:71: error: ‘FLT_EPSILON’ was not declared in this scope
     BOOST_CHECK(std::abs(output_parameters[1] - true_parameters[1]) < FLT_EPSILON);
                                                                       ^
Gpufit/Gpufit/tests/Brown_Dennis_Fit.cpp:71:71: error: ‘FLT_EPSILON’ was not declared in this scope
     BOOST_CHECK(std::abs(output_parameters[2] - true_parameters[2]) < FLT_EPSILON);
                                                                       ^
/Gpufit/Gpufit/tests/Brown_Dennis_Fit.cpp:72:71: error: ‘FLT_EPSILON’ was not declared in this scope
     BOOST_CHECK(std::abs(output_parameters[3] - true_parameters[3]) < FLT_EPSILON);

**Comment by MarcAntoine-Arnaud** [comment]
it require to add `#include <cfloat>` [here](https://github.com/gpufit/Gpufit/blob/master/Gpufit/tests/Brown_Dennis_Fit.cpp#L8)

**Comment by jkfindeisen** [comment]
Hi, it works for me on Ubuntu 16.04 and gcc 5.4. I'm surprised. 

Anyway, "cfloat" looks like it should do the trick on every system. Thanks Marc.

**Comment by Mannix1994** [comment]
thank you very much！
