### ISSUE TITLE
Why does CPUFIT_PROFILE run for more iterations than GPUFIT in 64-bit mode?

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#43]
With the same input data, CPUFIT runs for more iterations, on average, than GPUFIT.  It is a significant number - for 10^6 fits CPUFIT takes 4.35 iterations per fit and GPUFIT takes 3.9 iterations per fit.

Is the data being treated the same, internally?  Are the same types being used?

**Comment by superchromix** [comment]
I am labeling this as a bug, because if the two codes have the same algorithm, then the number of iterations should be the same.

**Comment by superchromix** [comment]
Note that this is for CPUFIT_PROFILE.  It looks like CPUFIT doesn't show this behavior.

**Comment by adrianjp88** [comment]
the tolerance of **GPUfit_profile** was set to a constant value, input tolerance was ignored. fixed.
