### ISSUE TITLE
Lower/Upper bound

### ISSUE THREAD

**Issue by ehna** [gpufit/Gpufit#43]
I am just wondering how can we add lower and upper bounds for parameters. Is there anyways to do so?

**Comment by Superzorg** [comment]
We have a similar requirement as well.  For example something similar to the scipy.optimize.curve_fit **bounds** option.  Any information as to whether there is a plan to include this in future versions would be greatly appreciated!

**Comment by simolorenzi** [comment]
I have the same need. Is there any possibility to do so?
I could try to implement that feature, but I need to know exactly in which function the iterations of the parameters are done.

**Comment by jkfindeisen** [comment]
Duplicate of #61
