### ISSUE TITLE
GPUFIT 64-bit running slow on P1020-Kiel

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#44]

**Comment by superchromix** [comment]
https://devtalk.nvidia.com/default/topic/963716/cuda-programming-and-performance/driver-jit-compilation/

**Comment by superchromix** [comment]
Bjorn would you please read the discussion above?

I would like to make sure that our compilation generates machine code for ALL cuda architectures, as described, and also that we are not relying on any JIT compilation when Gpufit runs.  This could be one reason why we are seeing slow performance on the GTX 1080 card.

**Comment by superchromix** [comment]
This is related to #46  -- the CMAKE file is very OPAQUE with regards to what CUDA options are being specified.  I can't find any examples in the CMAKE file explaining how to specify particular options, for example: if I want to add the flag "-gencode compute_30,sm_61" at compilation time, what do I do?  How do I change the CMAKE file?

**Comment by superchromix** [comment]
I am beginning to suspect that this issue may have to do with automatic GPU clock throttling.

**Comment by superchromix** [comment]
OK, I can't understand this problem.  I re-installed the video card driver, and also CUDA 8.0.  Rebuilt the binaries.  Now, both 32-bit and 64-bit GPUFIT are running slow.

I tried running GPU-Z to monitor the GPU clock speed and the GPU load, but this wasn't informative.

I tried running at GPU-intensive video benchmark WHILE running the matlab tests.  Even though the GPU clock speed was consistently high throughout the test, this had no effect on the matlab test results.

My current theory would be something to do with having to Just-In-Time compilation of the code, having to take place each time Gpufit is called.  ???

**Comment by bjoernthiel** [comment]
review #3 please

**Comment by jkfindeisen** [comment]
It might be worthwile to test with an older version of GPUfit (if available) in order to see if the problem was always or has been introduced when changing the cmake scripts before christmas.

**Comment by jkfindeisen** [comment]
"My current theory would be something to do with having to Just-In-Time compilation of the code, having to take place each time Gpufit is called. ???"

To measure the call overhead one could maybe call with zero number of fits. I did it for the Python binding (with lots of error checks) and I guess a single call overhead is worth about 2000 fits on a 5x5 pixel grid. So basically it all only pays off if one does a lot of fits at the same time. Of course the overhead needs to be minimized as much as possible anyway.

This should be part of the documentation.

**Comment by superchromix** [comment]
The point is that this particular slowdown is NOT happening on the other 
test machine (supergpu1) which has an older GPU and older CUDA version.

**Comment by bjoernthiel** [comment]
finding: running GPUFit_profile once unleashes GPUFit

**Comment by adrianjp88** [comment]
The reason of the slow execution was the use of the matlab binding [GpuFit.m](https://github.com/gpufit/GPUfit/blob/master/bindings/matlab/GpuFit.m) from this commit 6073d03efb7e748ac27a075432f78189e2a3a6ec. This m file unloads GPUfit after each call and thereby the calculation speed fits/sec goes down, especially for a small number of fits.
