### ISSUE TITLE
2D Gaussian MLE state 3 problem

### ISSUE THREAD

**Issue by bpisaacoff** [gpufit/Gpufit#45]
Hello, thank you for this awesome tool. 

We are running into a problem fitting to a 2D Gaussian with the MLE method in Matlab. The test data you provided runs correctly for 2D Gaussian MLE, and we have been successfully running the code on our own data doing 2D Gaussian fitting with the least-squares method, but whenever we run our own data with 2D Gaussian MLE a problem occurs. What happens is that all of the states outputted are state 3, which as far as I can tell means that the function is reaching a negative value. This is perplexing as we have carefully verified that we are not sending any negative values in the data or the parameters.

If you load the attached .mat file (in the .zip bc of GitHub) and run the following function call it should reproduce this problem. And as suggested earlier, it works correctly for least-squares.

`[parameters, states, chi_squares,~,~] = gpufit(dataset, [],model_id, initial_parameters, tolerance, max_n_iterations, params_to_fit, estimator_id, []);`

This seems like a bug in the MLE code to me, but it could be that we're doing something wrong. Regardless, I'd greatly appreciate any help you can provide.

Thank you very much,

[github_question.zip](https://github.com/gpufit/Gpufit/files/1725485/github_question.zip)

**Comment by superchromix** [comment]
This shouldn't happen - we will have a look.

**Comment by adrianjp88** [comment]
Thank you for the well prepared data for your test case. It was easy for me to reproduce the described behavior. Using the LSE method Gpufit outputs 0 states, but even so, the output parameters show, that the fitting process didn't run correctly. Your data is very noisy, and your initial parameters, especially the initial values for the amplitudes, don't fit to your data. Setting
`initial_parameters(1,:) = max(dataset) - min(dataset);`
`initial_parameters(5,:) = min(dataset);`
leads to much better results for both estimators.

**Comment by bpisaacoff** [comment]
Excellent thanks this did indeed solve the problem
