### ISSUE TITLE
No examples in the CMAKE file showing how to compile for a specific compute capability

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#46]

**Comment by superchromix** [comment]
there is no info in the cmake file.  I just have to guess how to change it.

**Comment by superchromix** [comment]
How do I specify a particular compilation flag?  A particular compute capability?  Is PTX code being generated?  Is JIT compilation required?

**Comment by jkfindeisen** [comment]
That's a case for http://gpufit.readthedocs.io/en/latest/installation.html#configuration-tips-via-cmake
We should extend it probably in an example style.

**Comment by superchromix** [comment]
it's good that this is in the docs, but there should also be some info 
in the actual cmake file (at least a pointer to the docs)

also, I clicked on the link, but it did not help much in showing me what 
to change in the cmake file...

**Comment by superchromix** [comment]
I can't find the NVCC compiler flags anywhere in Visual Studio (in the properties list of the Gpufit project).  Where are they??

**Comment by superchromix** [comment]
Would someone please update the CMAKE file or the docs to show how to do this?  Also, where can you find the full list of CUDA compiler flags that are set during compilation?

**Comment by bjoernthiel** [comment]
I use to group CMake files into sections # CMake, # CUDA, ... # Examples and so on. 
Using a smart editor (like Qt Creator, Notepad++, etc.) that provides syntax highlighting can also be of some help. 
The nvcc flags are set at the end of the CUDA section:
``` cmake
  list( APPEND CUDA_NVCC_FLAGS ${flags} )
```

**Comment by superchromix** [comment]
please add (several) examples...

**Comment by jkfindeisen** [comment]
"I can't find the NVCC compiler flags anywhere in Visual Studio (in the properties list of the Gpufit project). Where are they??"

Search for a cuda file in project GpuFit in the Solution Explorer, right click Properties, custom build tool, command line. This is autogenerated from cmake.

**Comment by jkfindeisen** [comment]
I guess Bjoern has to do it. He has most experience with cmake and visual studio. He is already assigned.

**Comment by bjoernthiel** [comment]
done
