### ISSUE TITLE
--use fast math option

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#47]
while reading this:

http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#axzz4WhMftgzT

I came across this compiler option.  Are we using it?  I can't tell because I don't know how to check the NVCC compiler flags.  Can we try it?  I don't know how to because there are no instructions for how to do this in the docs or the cmake file.

**Comment by adrianjp88** [comment]
We don't use this option. I executed the performance comparison for GPUfit compiled with the use_fast_math option and without it. Using the fast math option the mean number of iterations increased and the number of fits calculated per second decreased. Here the results for 10^6 fits:

***without** fast math*
  ***CPUfit***    24732.27 fits/s  |  x precision: 0.02800998  |  mean iterations: 3.92
  ***GPUfit***   **717875.09** fits/s  |  x precision: **0.02800997**  |  mean iterations: **3.92**
PERFORMANCE FACTOR CPU/GPU           **29.03**
***with** fast math*
  ***CPUfit***    24353.42 fits/s  |  x precision: 0.02802089  |  mean iterations: 3.92
  ***GPUfit***   **567214.97** fits/s  |  x precision: **0.02852671**  |  mean iterations: **6.97**
PERFORMANCE FACTOR CPU/GPU           **23.29**

**Comment by jkfindeisen** [comment]
So fast math is rather slow math?

What is fast math supposed to do?

**Comment by adrianjp88** [comment]
No, it is probably faster but less accurate. The decreased accuracy leads to increased number of iterations and this is the reason why the fitting process takes more time.

In detail the option
- enables the *"fast approximation mode"* instead of the *"IEEE round-to-nearest mode"* for division and square root operations on floats
- flushes denormal values to zero

**Comment by jkfindeisen** [comment]
Since it's actually slower and since it breaks compatibility with CPUfit I think we should not use it.

**Comment by superchromix** [comment]
good check on fast math.  yes let's not use it.
