### ISSUE TITLE
Should we require only CUDA 8 and newer?

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#48]
Seeing issue #45 and commit 7bd66b80f6db4d53707bdbcc08ecc7e5bfd4bf37 makes me wonder if we really need to support old CUDA versions. Where is the advantage? The CMake gets bigger and bigger.

On the other hand I wonder if we could check if there is a performance gain of using a newer CUDA version.

**Comment by superchromix** [comment]
I'm not sure what this issue means.  No, in general we don't want to force users to upgrade their CUDA.

**Comment by jkfindeisen** [comment]
It means that supporting older versions of CUDA means we need additional CMake code. It's not totally bad. But you're right. I might be one who actually does upgrade my CUDA, just to get max performance, but others might have reason to stay with older version, for example on Linux where 8.0 is not yet available. So, a clear no.
