### ISSUE TITLE
"invalid configuration argument"

### ISSUE THREAD

**Issue by lukkio88** [gpufit/Gpufit#48]
Hello,

I've implemented the following example for fitting a vector function rather complicated. I can't post the model, mostly because it's quite involved. But for the issue I'm pointing out I don't think it matters.

The following is my example

```
void my_model_fit_example() {

	//Generating sample test for fitting a vector function


	const size_t M = 12;
	const size_t N = M;
	
	const size_t X = 12; 
	const size_t Y = 12;
	const size_t n_channels = 3;
	const size_t n_dir_samples = X * Y;
	const size_t n_components = n_channels*M*N;
	const size_t n_fits = 1;
	const size_t n_points_per_fit = n_dir_samples * n_components; 
	const size_t n_model_parameters = 4 + 9*M*N;

	size_t temp, offset;

	// true parameters
	std::vector< float > real_params(n_fits*n_model_parameters);
	std::vector<float> init_params(n_fits*n_model_parameters);
	init_my_model_params(real_params, M, N);

	//random number generator
	// initialize random number generator
	std::mt19937 rng;
	rng.seed(0);
	std::uniform_real_distribution< float> uniform_dist(0, 1);

	//Let's perturbe a bit such parameters
	for (auto i = 0; i < n_fits*n_model_parameters; ++i) {
		init_params[i] = real_params[i] + uniform_dist(rng);
	}

	//centroids generator
	std::vector< float > x_coords(X);
	std::vector< float > y_coords(Y);
	for (auto i = 0; i < X; ++i) { //this for is silly given what I'm doing with it
		x_coords[i] = i;
		y_coords[i] = i;
	}

	//
	//
	//f = {
	//	g0(x[0],y[0]),
	//	...
	//	g3*MN-1(x[0],y[0]),
	//	...
	//	g0(x[i],y[j]),
	//	...
	//	g3*MN-1(x[i],y[j]),
	//	...
	//	};
	//
	std::vector< float > data(n_fits * n_points_per_fit);
	std::vector< float > curr_chunk_of_samples(n_components);
	size_t I, J;
	//iterating through directions
	for (size_t l = 0; l < X*Y; ++l) //if f(x,y,z) = (u(x,y,z),v(x,y,z)), the layout is {u(x[0],y[0],z[0]),v(x[0],y[0],z[0]),u(x[0],y[0],z[1]),v(x[0],y[0],z[1]),...,u(x[i],y[j],z[k]),v(x[i],y[j],z[k]),...}
	{

		J = l % X;
		I = l / X;
		//iterating through the pixels of this tile..
		my_model(x_coords[I], y_coords[J], real_params, curr_chunk_of_samples);
		for (auto k = 0; k < n_components; ++k) {
			data[l*n_components + k] = curr_chunk_of_samples[k];
		}
	}
	
	// tolerance
	float const tolerance = 0.001f;

	// maximum number of iterations
	int const max_number_iterations = 20;

	// estimator ID
	int const estimator_id = LSE;

	// model ID
	int const model_id = MY_MODEL;

	// parameters to fit (all of them)
	std::vector< int > parameters_to_fit(n_model_parameters, 1);

	// output parameters
	std::vector< float > output_parameters(n_fits * (4 + 9*M*N));
	std::vector< int > output_states(n_fits);
	std::vector< float > output_chi_square(n_fits);
	std::vector< int > output_number_iterations(n_fits);

	// call to gpufit (C interface)
	std::chrono::high_resolution_clock::time_point time_0 = std::chrono::high_resolution_clock::now();
	int const status = gpufit
	(
		n_fits,
		n_points_per_fit,
		data.data(),
		0,
		model_id,
		init_params.data(),
		tolerance,
		max_number_iterations,
		parameters_to_fit.data(),
		estimator_id,
		0,
		0,
		output_parameters.data(),
		output_states.data(),
		output_chi_square.data(),
		output_number_iterations.data()
	);

	std::chrono::high_resolution_clock::time_point time_1 = std::chrono::high_resolution_clock::now();
	
	// check status
	if (status != ReturnState::OK)
	{
		throw std::runtime_error(gpufit_get_last_error());
	}

	// print execution time
	std::cout << "execution time "
		<< std::chrono::duration_cast<std::chrono::milliseconds>(time_1 - time_0).count() << " ms" << std::endl;

 	std::cout << "Finished!" << std::endl;
}
```

I've run my example in debug mode and what I see is that an exception is thrown when the following is reached:
```

void LMFitCUDA::run()
{
    // initialize the chi-square values
	calc_curve_values();
    calc_chi_squares();
    calc_gradients();
    calc_hessians(); //THIS LINE!!!

    gpu_data_.copy(
        gpu_data_.prev_chi_squares_,
        gpu_data_.chi_squares_,
        n_fits_);

    // loop over the fit iterations
    for (int iteration = 0; !all_finished_; iteration++)
    {
        // modify step width
        // Gauss Jordan
        // update fitting parameters
        solve_equation_system();

        // calculate fitting curve values and its derivatives
        // calculate chi-squares, gradients and hessians
		calc_curve_values();
        calc_chi_squares();
        calc_gradients();
        calc_hessians();

        // check which fits have converged
        // flag finished fits
        // check whether all fits finished
        // save the number of needed iterations by each fitting process
        // check whether chi-squares are increasing or decreasing
        // update chi-squares, curve parameters and lambdas
        evaluate_iteration(iteration);
    }
}
```

The thrown exception is `"invalid configuration argument"`, not sure what this exception mean. My model both implements calculation of function value and derivatives (jacobian to be more specific is a vector function the one I have to fit), the estimator I'm using is the LSE provided by the tool.

Anyway I do wonder what can be the problem. I cannot post the whole function for several reasons, but I can post the for loops eventually (in order to understand from where to where I'm iterating). I'm saying this because I can see the hessian calculation is based on the derivatives, which are implemented in my model.

Can anyone help?

**Comment by adrianjp88** [comment]
Hi, the reason why you get this error is because of the large number of model parameters. The number of threads per block is limited to **1024** (see [CUDA compute capabilities](http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities)). The CUDA kernel function calculating the hessian is configured to execute **n_model_parameters*n_model_parameters** threads per block. So, the number of model parameters, that can be fit by Gpufit is limited to **32**.

**Comment by lukkio88** [comment]
Is there anything you can suggest to work around the problem?  Could hacking the code in some point allow me to do the computation? I'm aware the number of parameters is a lot, but that's actually what I need to do.

If this cannot be fixed that means I have to adapt my problem in such a way I won't have to fit more than 32 parameters, is that right?

However I'm a bit confused, I don't know all the implementation details in GPUFit, but if the number of threads per block is 1024, why is the number of parameters that can be fit limited to 32?

**Comment by superchromix** [comment]
The code is calculating one Hessian matrix in one thread block - this imposes the limitation due to the maximum number of threads per block.

We plan to modify the Hessian calculation to allow a single Hessian to be calculated over multiple thread blocks, which would remove the limitation.  For now, however, the maximum number of fit parameters is indeed 32.

**Comment by lukkio88** [comment]
Ok, say T32 is the time taken to fit a 32 parameters function, do you think the time would scale linearly for a multiple of 32? like would be T64 = 2*T32 for example, etc. I can easily design an experiment for 32 parameters, but I would need to know how this would scale. Also how have you extrapolated the "32" from the number of threads per block, which is "1024"?

**Comment by superchromix** [comment]
32^2 = 1024....

The calculation time should be approximately the same for 64 parameters as for 32 parameters, since the calculations are running in parallel.  However, the 64-parameter fit requires a 4x the number of threads, so this may limit the number of fits that can run in each chunk.

**Comment by lukkio88** [comment]
> 32^2 = 1024....

I got that but I can't find the relationship  between the threads and how they're used to compute the parameters, and from there the 32. It seems to me that 32 threads contribute somehow to update a single parameter, but I don't get how.

**Comment by lukkio88** [comment]
I'm reading through the code, I'm not a cuda expert, but it might be possible I need to hack the following:

```
void LMFitCUDA::calc_hessians()
{
    dim3  threads(1, 1, 1);
    dim3  blocks(1, 1, 1);

    threads.x = info_.n_parameters_to_fit_;
    threads.y = info_.n_parameters_to_fit_;
    blocks.x = n_fits_;

    cuda_calculate_hessians <<< blocks, threads >>>(
        gpu_data_.hessians_,
        gpu_data_.data_,
        gpu_data_.values_,
        gpu_data_.derivatives_,
        gpu_data_.weights_,
        info_.n_points_,
        info_.n_parameters_,
        info_.n_parameters_to_fit_,
        gpu_data_.parameters_to_fit_indices_,
        info_.estimator_id_,
        gpu_data_.iteration_failed_,
        gpu_data_.finished_,
        gpu_data_.user_info_,
        info_.user_info_size_);
    CUDA_CHECK_STATUS(cudaGetLastError());
}
```

**Comment by lukkio88** [comment]
I think I got why, if `n` is the number of parameters to be fit, the hessian will have `n^2` entries. You run a thread for each entry of the hessian matrix I guess, but each entry contains cross-information between parameter `i` and `j`.

**Comment by superchromix** [comment]
The limitation on the number of model parameters has been lifted.  Fit model functions can now have up to 1024 parameters.
