### ISSUE TITLE
Make binary distribution

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#49]
distribution should include:

Test executable
GPUFIT DLL
CPUFIT DLL
Matlab binding
Python binding

**Comment by jkfindeisen** [comment]
You really closed issue #10 just to open a very similar one?

**Comment by superchromix** [comment]
issue #10 was a discussion about whether we needed a binary distribution ;)

**Comment by jkfindeisen** [comment]
Do we need to include 32 bit binaries for Windows? If so, they need to be tested with a 32 bit Matlab/Python most probably.

**Comment by jkfindeisen** [comment]
We need to discuss it. Among the difficulties are:

- CUDA always needs to be installed (which version)
- Python 3 requires 32/64 bit
- which runtimes need to be installed

A try at a more refined distribution:

./Readme (Short)
./Manual.pdf
./application/Readme for application
./application/Performance-Test-GPU/CPU.exe
./application/GPUfit.dll/CPUfit.dll
./python/Reade for python
./python/wheel
./matlab/Readme for matlab
./matlab/toolbox

We should not include installers for CUDA and runtimes but rather we should expect the users to install them themselves. We should guide the user which combinations should be used.

Python wheel only build with VS 2015 (will then require at least CUDA 8) ?
Matlab toolbox for VS 20015 and CUDA 8 (Matlab 2015a and higher) but also for VS 2013 CUDA 7.5 (also works with Matlab 2014 and maybe lower)?

**Comment by jkfindeisen** [comment]
Matlab compiler support: https://www.mathworks.com/support/sysreq/previous_releases.html

**Comment by jkfindeisen** [comment]
I looked at other notable GPU open source libraries how and if they distribute binary packages.

- CUDPP (https://cudpp.github.io/) only distributes source
- cuBLAS (https://developer.nvidia.com/cublas) part of CUDA
- cuFFT (https://developer.nvidia.com/cufft) part of CUDA
- pyCUDA (https://mathema.tician.de/software/pycuda/) only provides its sources
- Thrust (https://developer.nvidia.com/thrust) part of Nvidia
- CULA (http://www.culatools.com/) requires login to download, seem to deliver binaries, requires CUDA to be installed
- Magma (http://icl.cs.utk.edu/magma/) only delivers the source
- NanoJ-SRRF (https://bitbucket.org/rhenriqueslab/nanoj-srrf/wiki/Home) uses OpenCL, not CUDA
- JCUDA (http://jcuda.org/jcuda/JCuda.html) 

See also: www.cs.du.edu/~dconnors/courses/GPUarchitecture/notes/tools.pdf

**Comment by jkfindeisen** [comment]
The whole thing then should be zipped and a suitable github commit tagged and the zip file attached.

**Comment by jkfindeisen** [comment]
One question of Björn was if the ctypes module of Python differs for Python 3.x versions? I don't know.

**Comment by jkfindeisen** [comment]
What about the license of the binary package? At least a "as is" but probably the "MIT" or "BSD" license I guess.

**Comment by jkfindeisen** [comment]
The manual should actually not be taken from readthedocs but rather made locally (by calling "docs/make.bat latex" and then compiling the tex with miktex for example) because it looks much nicer this way (for example there are automatic line wraps in the code section while readthedocs doesn't have this.

**Comment by jkfindeisen** [comment]
In 7eaf66242082e1dd7af651c0483064730c7e7926 I created a setup.py file which if executed
`python setup.py bdist_wheel`
generates a wheel file of name pyGPUfit-1.0.0-py3-none-any.whl which seems to contain the right files.

You need
/gpufit/__init__.py
/gpufit/gpufit.py
/gpufit/GpuFit.dll
/gpufit/xxx.dll (runtime?)
/setup.py
/setup.cfg
/README.md
/version.py (not currently but probably in the future)

That is, more or less the whole contents of bindings/python into $output/pyGPUfit and bindings/python/gpufit into $ouput/pyGPUfit/gpufit plus copying the GPUfit library and the runtime into $output/pyGPUfit/gpufit before calling $output/pyGPUfit/setup.py bdist_wheel which will produce a wheel file in $output/pyGPUfit/dist.

**Comment by jkfindeisen** [comment]
Making a binary for distribution makes only sense with **CUDA compile all**, that is for all architectures code is built. However for testing purposes we maybe should not enforce this. Should we print a warning then at least?

**Comment by jkfindeisen** [comment]
When I run PACKAGE it creates
package: xxx/GPUfit-0.1.1-win64.zip generated.

how does it arrive at 0.1.1 as version number? The project version in CMakeList is 1.0.0?

**Comment by adrianjp88** [comment]
I think the package version must be set separately i.e.
set( CPACK_PACKAGE_VERSION_MAJOR 1 )
set( CPACK_PACKAGE_VERSION_MINOR 0 )
set( CPACK_PACKAGE_VERSION_PATCH 0 )

**Comment by bjoernthiel** [comment]
set( CPACK_PACKAGE_VERSION ${PROJECT_VERSION} )

**Comment by jkfindeisen** [comment]
For Jan: make the Python binding 2.X compatible

**Comment by jkfindeisen** [comment]
Btw. Matlab does not make 32 bit versions on Windows anymore since 2015b. See also their plattform roadmap: https://www.mathworks.com/support/sysreq/roadmap.html

**Comment by jkfindeisen** [comment]
Python 2.X support won't happen now because I used enums which were only introduced in version 3.4+ and are not officially backported. I could work around that, specifically I could not use enums, but I won't do that now and only if heavily asked for from the outside (it's not difficult though).

**Comment by jkfindeisen** [comment]
I semi-automatically created and tested our very first binary using package/create_package.bat. Therefore I close this issue.

Still remains:
Some better targets (application, python, python wheel, matlab) using install insted of cmake copy.
Making the package targets running matlab and python accordingly
Create package only if cuda_architecture==All?
