### ISSUE TITLE
Error reporting in GPUfit

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#5]
We need an error reporting mechanism, so that the code can fail gracefully rather than just crash.  We can do this after the paper submission.

**Comment by jkfindeisen** [comment]
For the bindings we have the problem that we use the C interface, so just forwarding C++ exceptions is not possible, nor recommended. The standard way is something like catching all exceptions, returning an error code and having a function like last_error or throwing errors in the native environments (Python, Matlab, ...).

**Comment by bjoernthiel** [comment]
implemented
