### ISSUE TITLE
Make performance test executable

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#50]
Test executable should use GPUFIT and CPUFIT to run fits on randomized gaussian test data.  Initial guesses should also be randomized.  Performance should be reported in terms of fit precision (X coordinate only), number of fits per second, and mean number of iterations.  The code should automatically run a series of tests with varying numbers of fits from 1 to 10^6.

**Comment by jkfindeisen** [comment]
There is one now. Is it already in the final state?

**Comment by jkfindeisen** [comment]
Nobody commented and it looks good to me.
