### ISSUE TITLE
GPUFit VS project issues, debugging problems

### ISSUE THREAD

**Issue by lukkio88** [gpufit/Gpufit#51]
Hello,

I'm trying to debug some of the cuda kernels I've hacked a bit in the GPUFit, but for some reason the CUDA debugger skips all the breakpoints. Also there's something else wrong, no CUDA C/C++ tab appears in the project properties.

I'm trying to follow this to sort out the problem:
[(https://stackoverflow.com/questions/10813260/cuda-c-tab-in-project-properties)]

Can anyone suggest where those rules should be copied?

**Comment by superchromix** [comment]
This issue is with VS / CUDA development, not Gpufit.  Please keep the issues to things specific to the Gpufit software.
