### ISSUE TITLE
Installation and raw data used in the paper?

### ISSUE THREAD

**Issue by ghost** [gpufit/Gpufit#52]
Dear all,
1- I will try to use GPUFIT which seems to be really useful even if I did not found the PDF documentation and I don't know from which point I should start to use GPUFIT.
2- Could you put in the repository raw data used for your tests please?
Best regards.

**Comment by jkfindeisen** [comment]
Documentation is automatically generated from the source repository and stored as [web site](http://gpufit.readthedocs.io/en/latest/?badge=latest) or as [PDF](https://media.readthedocs.org/pdf/gpufit/latest/gpufit.pdf) or as part of the binary package of a [release](https://github.com/gpufit/Gpufit/releases).

There are unit tests in the Gpufit project, but they generate their test data on the fly. What kind of raw data would you actually expect to be part of the repository?

**Comment by ghost** [comment]
Thanks for your really quick answer!
I would expect the data used for the main figure (Figure 1) which is really your benchmark corresponding to your best (and amazing) results. I would like to test this beautiful image of nuclear pore.
Finally, two things are unclear for me:
1- the size of the data you used (image frame size and number of frames) which is missing so we don't know precisely if our data can be easily supported by your amzingly fast software!
2- you speak about fits/s but generally, people speak about localization/s or frame/s, which is different when two steps are required (detection + estimation)

Best regards.

**Comment by superchromix** [comment]
Don't let there be any confusion between curve fitting and PALM/STORM data analysis.  Gpufit is a general purpose curve fitting software, with many applications, one of which is analyzing localization microscopy data.  As stated, however, Gpufit is designed to carry out one task: curve fitting.  If you want to use it for analyzing localization microscopy data, you would need to integrate it into a software specifically designed to do that.  In the example for the paper, we integrated Gpufit into the Picasso software.

**Comment by superchromix** [comment]
The speed of execution will depend on the CPU and GPU hardware in use, so providing test data doesn't serve much purpose since the speed will change depending on your computer.  The details of how to generate the test data are in the Supplemental Info.

**Comment by ghost** [comment]
Thank you.
This is more clear now for the purpose of this software. The fitting performances are really impressive!
I expected to find the image information more easily like 512x512x1000 frames for example. This would help a lot comparison with other techniques of fitting.
Best
