### ISSUE TITLE
Running 'make' on Linux

### ISSUE THREAD

**Issue by benjiebob** [gpufit/Gpufit#53]
Hi, I'm having issues installing this library. The cmake step passed successfully but I still get errors on the make:

In file included from /scratch/bjb56/download/Gpufit/Gpufit/gpufit.cpp:2:0:
/scratch/bjb56/download/Gpufit/Gpufit/interface.h:6:14: error: expected constructor, destructor, or type conversion before ‘(’ token
 static_assert( sizeof( int ) == 4, "32 bit 'int' type required" ) ;
              ^
/scratch/bjb56/download/Gpufit/Gpufit/gpufit.cpp: In function ‘int gpufit(size_t, size_t, float*, float*, int, float*, float, int, int*, int, size_t, char*, float*, int*, float*, int*)’:
/scratch/bjb56/download/Gpufit/Gpufit/gpufit.cpp:48:12: error: ‘ReturnState’ is not a class or namespace
     return ReturnState::OK ;
            ^
/scratch/bjb56/download/Gpufit/Gpufit/gpufit.cpp:54:12: error: ‘ReturnState’ is not a class or namespace
     return ReturnState::ERROR ;
            ^
/scratch/bjb56/download/Gpufit/Gpufit/gpufit.cpp:60:12: error: ‘ReturnState’ is not a class or namespace
     return ReturnState::ERROR;
            ^
/scratch/bjb56/download/Gpufit/Gpufit/gpufit.cpp: In function ‘int gpufit_get_cuda_version(int*, int*)’:
/scratch/bjb56/download/Gpufit/Gpufit/gpufit.cpp:90:16: error: ‘ReturnState’ is not a class or namespace
         return ReturnState::OK;
                ^
/scratch/bjb56/download/Gpufit/Gpufit/gpufit.cpp:96:16: error: ‘ReturnState’ is not a class or namespace
         return ReturnState::ERROR;
                ^
CMakeFiles/Gpufit.dir/build.make:90: recipe for target 'CMakeFiles/Gpufit.dir/gpufit.o' failed
make[2]: *** [CMakeFiles/Gpufit.dir/gpufit.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Gpufit.dir/all' failed
make[1]: *** [CMakeFiles/Gpufit.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Any tips would come much appreciated.

Thanks,

Ben

**Comment by superchromix** [comment]
Can you please provide details of your OS, compiler, and CUDA version?

**Comment by lifangda01** [comment]
I encountered this while running Cmake with `../Gpufit` in the build directory as suggested in the docs. The fix for me was to run Cmake with `..` instead.

**Comment by jkfindeisen** [comment]
The original error by benjiebob is likely related to https://stackoverflow.com/questions/5188554/my-enum-is-not-a-class-or-namespace and a real bug on Linux with older compilers (gcc < 4.5) that didn't know yet the C++11 standard. However, by now this should not be an issue anymore and we want to keep scoped enums.
