### ISSUE TITLE
Point spread funtion

### ISSUE THREAD

**Issue by yuanshuoastro** [gpufit/Gpufit#54]
dear all,
is there any psf https://en.wikipedia.org/wiki/Point_spread_function  support here?

**Comment by jkfindeisen** [comment]
Gpufit is a general purpose fitting package and by customizing the model function any effect of any PSF can conveniently by included. What kind of support would you expect?

Please note that the inbuilt model functions already demonstrate the working of a PSF. For a single emitter a convolution with a PSF (a Gaussian in the inbuilt model functions) is just a shifted and scaled reproduction of the PSF, which the model functions indeed compute.

**Comment by yuanshuoastro** [comment]
@jkfindeisen Thank you for your reply.
the psf can be extracted by test light source or by instruments, say in Gaussian of some parameterized 
equations.

Thank you for pointing out the inbuild psf for me. In practice, the parameters of the psf might be change in different image position.
