### ISSUE TITLE
Ubuntu compilation problem

### ISSUE THREAD

**Issue by aaristov** [gpufit/Gpufit#55]
Hi,

I'm having troubles running `make` after cmake on ubuntu machine with CUDA 9. Could you help please?

> [ 56%] Building NVCC (Device) object Gpufit/examples/CMakeFiles/CUDA_Interface_Example.dir/CUDA_Interface_Example_generated_CUDA_Interface_Example.cu.o
In file included from /usr/include/c++/4.8/random:35:0,
                 from /home/andrey/Downloads/Gpufit/Gpufit/examples/CUDA_Interface_Example.cu:4:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
CMake Error at CUDA_Interface_Example_generated_CUDA_Interface_Example.cu.o.RELEASE.cmake:221 (message):
  Error generating
  /home/andrey/Downloads/Gpufit/Gpufit/examples/CMakeFiles/CUDA_Interface_Example.dir//./CUDA_Interface_Example_generated_CUDA_Interface_Example.cu.o

> make[2]:

***

> [Gpufit/examples/CMakeFiles/CUDA_Interface_Example.dir/CUDA_Interface_Example_generated_CUDA_Interface_Example.cu.o] Error 1
make[1]: *** [Gpufit/examples/CMakeFiles/CUDA_Interface_Example.dir/all] Error 2
make: *** [all] Error 2

**Comment by adrianjp88** [comment]
Thank you for reporting the issue. The recently included CUDA interface example is using C++11 expressions. On Linux the NVCC compiler is not using the C++11 standard by default. It's fixed by the last commit 6039e9353936b28cfe22304ad2611b289ddb32be

**Comment by aaristov** [comment]
Thanks, works like a charm!
