### ISSUE TITLE
Example needed 

### ISSUE THREAD

**Issue by jancoow** [gpufit/Gpufit#56]
Hi,

I want to use the Gpufit library in python. I successfully compiled it and installed the python library. However I need some help with using it.

I want to move on from the [numpy polyfit](https://docs.scipy.org/doc/numpy/reference/generated/numpy.polyfit.html) to this library so I can analyze large datasets faster. However I'm unable to calculate the polynomial coefficients. I can't figure out how I can insert my datasets. I've bot the X-values and Y-values available in numpy arrays. I tried to pass a 2d array to the data parameter, but I can't get it working.
Also I can't find where I can set the degree of the fitting polynomial. 

Could someone provide me a simple example which calculates the polynomial coefficients with a dataset x,y as input?

**Comment by superchromix** [comment]
To accomplish this, you will start by writing a model function for the polynomial of degree N (whichever order you need).  If you want to pass in the X values (necessary if your data points are not evenly spaced in X) you will do this via the user info parameter.

**Comment by jancoow** [comment]
Ah, so this means that a polynomial fit is not implemented? So I need to write it myself?

**Comment by superchromix** [comment]
Yes, but this should not be difficult, following the examples provided in the docs.  If you write the function, please post it here and we can provide comments or include it into the standard distribution.

**Comment by jkfindeisen** [comment]
A long time passed and the documentation has a section about writing custom model functions or custom estimators (https://gpufit.readthedocs.io/en/latest/customization.html). I close this issue because the creator is likely not interested in this anymore. If this is wrong, please comment again.
