### ISSUE TITLE
Java environment variables should not require setting

### ISSUE THREAD

**Issue by superchromix** [gpufit/Gpufit#57]
... in order to build.  This seems to be only a gradle requirement.  The path to java and the JDK can be set in other ways:
https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version

**Comment by jkfindeisen** [comment]
In d7c3832cb6ae0ec39c928fc96b2bba25d67c819a we now get the JDK home directory from CMAKE. If this fails (not tested on Linux for example), we will instruct the user to insert the desired JDK home path manually in a gradle.properties file in the project directory. One way or the other JAVA_HOME is not needed anymore.

**Comment by superchromix** [comment]
still happening

**Comment by superchromix** [comment]
fixed
