### ISSUE TITLE
Inconsistent Poisson MLE estimator

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#57]
The estimator multiplies by two and subtracts the data (in the paper, in the docs and even in the code). That's not necessary for minimization and reduces the computational speed. Use instead the usual estimator everyone else uses: model - data * log model
and also use the derivatives of it.

**Comment by jkfindeisen** [comment]
Or does the hessian already do it like this in https://github.com/gpufit/GPUfit/blob/master/GPU_Fit/mle.cuh?

**Comment by jkfindeisen** [comment]
Maybe related to this: if you let the Gaussian 2D examples run (in Python or Matlab or C++) they consistently estimate the amplitude and the background level wrong if the amplitude is on the order of the background level, i.e. the ampltiude is significantly overestimated and the background level underestimated. Of course MLE estimators can be biased, so it may even be a real effect.

In any case it doesn't seems to be a simple bug. Does anyone has an idea? Do you see it for the other tests?This should probably be solved.

**Comment by jkfindeisen** [comment]
I changed the scope of this slightly and label it tentatively as a bug and assign also Adrian who will test the very same example against an independent fit algorithm (GPULMfit or CMinpack or ...).

**Comment by jkfindeisen** [comment]
Adrian reports the same effect for LSE.

**Comment by adrianjp88** [comment]
I ran the matlab test gpufit_gauss2d() for GPUfit and GPU-LMFit. To get comparable results the tolerance is increased to 0.01. The results are the same for both implementations
p1 true  10.00 mean  10.78 std   0.00
p2 true   5.50 mean   5.35 std   0.00
p3 true   5.50 mean   5.78 std   0.00
p4 true   3.00 mean   2.57 std   0.00
p5 true  10.00 mean  10.20 std   0.00

**Comment by adrianjp88** [comment]
I also compared GPUfit and cminpack using this test with the tolerance 0.0001. cminpack shows a similar behavior as GPUfit.

**GPUfit:**
- p1 true  10.00 mean  10.79 std   2.86
- p2 true   5.50 mean   5.50 std   0.33
- p3 true   5.50 mean   5.50 std   0.33
- p4 true   3.00 mean   3.09 std   0.87
- p5 true  10.00 mean   9.53 std   3.05

**cminpack:**
- p1 true  10.00 mean  10.85 std   4.59
- p2 true   5.50 mean   5.50 std   0.33
- p3 true   5.50 mean   5.50 std   0.33
- p4 true   3.00 mean   3.10 std   0.97
- p5 true  10.00 mean   9.47 std   4.76

**Comment by jkfindeisen** [comment]
I will run it against Matlab using Poisson ML and with larger fit sizes, just to make sure the deviance is not on our side.

**Comment by jkfindeisen** [comment]
I did it and Matlab gives the same result. So we are not only sure it's not a bug, we are even seeing the breaking down of MLE here. Nice example. The more efficient computation issue here I disregard for now. Someone of us will surely revisit the kernels sooner or later.
