### ISSUE TITLE
Filling out the documentation

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#6]
More detail in the documentation, particularly with regards to the code interface.  Also updating the docs to the new code interface.  Also adding documentation for the python interface.  Jan generously volunteered to do this 👍 .

**Comment by jkfindeisen** [comment]
Yes, I do.

**Comment by bjoernthiel** [comment]
API documentation is outdated already

**Comment by jkfindeisen** [comment]
now less outdated, still a couple of things to do:

- specific build instructions on linux and mac-os
- example of user_info (straight_line_fit)
- python/matlab example (in the repo and a link in the docs)

**Comment by adrianjp88** [comment]
A matlab example is included now.

**Comment by jkfindeisen** [comment]
And a Python example as well, they are in code and linked to in the docs.

**Comment by jkfindeisen** [comment]
We still need:

- more introduction (like in the paper) with references
- describe return value of gpufit (status) and status of each fit (output_fit_states) more thoroughly
- examples enumerated and also non-working steps (passing user-info, ...)

**Comment by jkfindeisen** [comment]
Sorry, I need to close it. It's unmanageable to have so many issues combined.
