### ISSUE TITLE
model problem

### ISSUE THREAD

**Issue by Mannix1994** [gpufit/Gpufit#60]
When I add a polynominal model to Gpufit, it works correctly.
but when I add this model: f(x) = p[0]/(1 + exp(p[1] *x + p[2])) + p[3] , which is a sigmoid function, it don`t works, the hessian matrix is always singular, can you help me error in the model file(sigmoid.cuh) ?
here is my code:
```
//sigmoid.cuh
__device__ void calculate_sigmoid(
    float const * p,
    int const n_fits,
    int const n_points,
    float * value,
    float * derivative,
    int const point_index,
    int const fit_index,
    int const chunk_index,
    char * user_info,//An input vector from -5 to 5 as the (X) coordinate
    std::size_t const user_info_size)
{
    // indices

    float * user_info_float = (float*) user_info;
    float x = 0.0f;
    if (!user_info_float)
    {
        x = point_index;
    }
    else if (user_info_size / sizeof(float) == n_points)
    {
        x = user_info_float[point_index];
    }
    else if (user_info_size / sizeof(float) > n_points)
    {
        int const chunk_begin = chunk_index * n_fits * n_points;
        int const fit_begin = fit_index * n_points;
        x = user_info_float[chunk_begin + fit_begin + point_index];
    }

    // value
    value[point_index] = p[0] / (1.0 + exp(p[1] * x + p[2])) + p[3];

    // derivatives
    float * current_derivatives = derivative + point_index;
    float A = p[0], B = p[1], C = p[2];
    float expBC = exp(B*x + C);
    float expBC1 = 1.0f+expBC;
    current_derivatives[0 * n_points] = (1.0f/expBC1);
    current_derivatives[1 * n_points] = ((-A/(expBC1*expBC1))*x*expBC);
    current_derivatives[2 * n_points] = ((-A/(expBC1*expBC1))*expBC);
    current_derivatives[3 * n_points] = 1.f;
}
```

**Comment by superchromix** [comment]
Is this an issue of numerical precision?  What are the magnitudes of the parameters and the X values?

**Comment by Mannix1994** [comment]
I don`t know if it is an issue of numerical precision. the size of parameters is 4, which are p[0], p[1] ,p[2] and  p[3] mentioned above. the the size of X is 15,  from -5 to 5. thanks for your response!

**Comment by superchromix** [comment]
Can you post a file with the actual data you are trying to fit, and the initial values of your parameters?

**Comment by Mannix1994** [comment]
Sorry to reply you after so many months.
here is an array of actual data
`1.12133 1.12133 1.10914 1.11524 1.13352 1.10305 1.01163 0.853186 0.78615 0.822715 0.822715`
my initial value is
 `0 0 0 0`
so, the he hessian matrix is always singular. I tried to change initial values to non-zero values, it works very well !!!
this is a amazing project !!!
Thanks for your project !!! Thank you very mush !!!
