### ISSUE TITLE
Upper and lower bound for parameters

### ISSUE THREAD

**Issue by ryohachiuma** [gpufit/Gpufit#61]
Hi, 

Thank you for providing the great implementation!

I'm working now on estimating superquadric parameters (Eq. 3) in 
http://eprints.fri.uni-lj.si/34/1/PAMI_1997.pdf

There are lower and upper bound for estimated parameters. 

Can we set upper and lower bound for parameter estimation?

Thanks,

**Comment by jkfindeisen** [comment]
No, you cannot set upper and lower bounds on parameters in the current version.

**Comment by jkfindeisen** [comment]
In the mean time it was implemented, but still need to be documented properly.

**Comment by jkfindeisen** [comment]
Is well documented now.
