### ISSUE TITLE
Bundle Adjustment

### ISSUE THREAD

**Issue by RamadanAhmed** [gpufit/Gpufit#62]
Hi,
Is that possible to use gpufit to solve bundle adjustment problem ? and if possible could anyone provide example
Thanks

**Comment by jkfindeisen** [comment]
If you can formulate the bundle adjustment problem as an optimization problem suitable for the Levenberg-Marquardt algorithm, then very likely Gpufit can do it.  What would need to be implemented is a custom fit model function and possibly also an estimator function specific to bundle adjustment problems. So far, there are no examples for this.

A general way to implement a custom fit model is described in the [customization section](http://gpufit.readthedocs.io/en/latest/customization.html) of the documentation.
