### ISSUE TITLE
Please freeze the code (GPUFIT and CPUFIT)

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#62]
so that I can continue making the final performance evaluations

**Comment by jkfindeisen** [comment]
I think the branching mechanism is perfectly suited for that. I created a branch called "publication" for this purpose. It will not get any code changes anymore but only documentation changes and maybe code to produce binaries. Please use this branch!

https://github.com/gpufit/GPUfit/tree/publication

Please all note that we continue working on the master branch and suitable commits and then applied also on the publication branch. **This requires that we appropriately separate code changes from other changes in the commits. You'll have to be a bit more careful how you commit.**

**Comment by superchromix** [comment]
Bjorn should do this after his final commits are made

**Comment by superchromix** [comment]
waiting for Bjorn and Adrian on this.

**Comment by jkfindeisen** [comment]
I also need to change a small thing in the Python binding.

**Comment by jkfindeisen** [comment]
I deleted the unused new branch. It should only be created at the moment of the code freeze. I updated python bindings and tests. Now I will only update documentation.

**Comment by jkfindeisen** [comment]
See branch https://github.com/gpufit/GPUfit/tree/publication

**Comment by jkfindeisen** [comment]
So much for the code freeze. We changed the code at least two times quite a lot. That's why I will delete the publication branch (it's useless) and tag the master branch upon submission instead.
