### ISSUE TITLE
Test and Example of linear fit with user info should have type float

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#64]
If we have user_info to have non-linear spaced data points then they should be stored as float, not int.

In https://github.com/gpufit/GPUfit/blob/master/GPUfit/tests/Linear_Fit_1D.cpp, https://github.com/gpufit/GPUfit/blob/master/GPUfit/examples/Linear_Regression_Example.cpp and https://github.com/gpufit/GPUfit/blob/master/GPUfit/linear1d.cuh

they are used as int. It should be changed to float there.

**Comment by jkfindeisen** [comment]
Solved for GPUfit in 83381124d6cfcb8ca3c85599f309a17e17613ca6 Cannot solve in CPUfit because of issues #35 and issue #41 .

**Comment by adrianjp88** [comment]
solved for CPUfit as well
