### ISSUE TITLE
Python Binding for new Fit Model / Estimator

### ISSUE THREAD

**Issue by johoe** [gpufit/Gpufit#64]
It is necessary to update the \Gpufit\python\pygpufit\pgufit.py in order to use a new Fit Model or Estimator from Python.

This should be included in the docs.

**Comment by jkfindeisen** [comment]
I agree that this should be mentioned. The C interface itself only knows integer values for the model and estimator types, the model and estimator classes in Python, Java, Matlab are more for convenience. The documentation will be updated and further improved in one of the following commits.

**Comment by superchromix** [comment]
I should add that, at this time, **double precision is NOT officially supported** in the Gpufit library.  Although the framework exists in the C code, none of the bindings will work with double precision.

The option to compile Gpufit with double precision math was added for debugging purposes, and the code has not been fully tested in this mode.  On many GPUs the code will run drastically slower with double precision floating point.

Feel free to tinker with the bindings to get double precision working for your application - this should not be too difficult.  Let us know how it goes.

**Comment by jkfindeisen** [comment]
wrong issue
