### ISSUE TITLE
No suitable Matlab and/or MX_Library version found - skipping Gpufit Matlab binding!

### ISSUE THREAD

**Issue by drbeiliu** [gpufit/Gpufit#65]
I tried to use cmake-gui to build Gpufit from the source with MATLAB binding. I set Matlab_WORKING_DIRECTORY in cmake-gui while doing configuration, but it always shows me 'No suitable Matlab and/or MX_Library version found - skipping Gpufit Matlab binding!'. I don't have matlab 2014 in hand, but I tried matlab 2016-2018, and none of them worked out. Any thoughts? Thanks.

**Comment by jkfindeisen** [comment]
The Matlab_WORKING_DIRECTORY is setting the Matlab current folder when starting from Visual Studio.
The Matlab detection in CMake is made by CMake ("find_package( Matlab COMPONENTS MX_LIBRARY )"). Usually it works also for Matlab 2016-18 but it may not find Matlab in your case. Depending on your OS and the way you installed Matlab I would check with CMake until the single line ("find_package( Matlab COMPONENTS MX_LIBRARY )") works for you in any CMake file.

**Comment by minkowsk** [comment]
> I tried to use cmake-gui to build Gpufit from the source with MATLAB binding. I set Matlab_WORKING_DIRECTORY in cmake-gui while doing configuration, but it always shows me 'No suitable Matlab and/or MX_Library version found - skipping Gpufit Matlab binding!'. I don't have matlab 2014 in hand, but I tried matlab 2016-2018, and none of them worked out. Any thoughts? Thanks.

Have you solved it?

**Comment by superchromix** [comment]
Are you configuring the project for the correct architecture?  i.e. 32-bit vs. 64-bit?  If you are building for x64, you also need to have 64-bit matlab installed in order for cmake to find the correct package.

**Comment by willschmid** [comment]
I am seeing the same "skipping Gpufit Matlab binding!" notification while trying to build Gpufit from both the command line and GUI. Where and how exactly do I set/change Matlab_WORKING_DIRECTORY (I am inexperienced with CMake)? I am confident I am building for the correct architecture (x64). Thank you!

**Comment by jkfindeisen** [comment]
I tried it again and I cannot reproduce the problem.

CMake automatically detects Matlab with the command `find_package( Matlab COMPONENTS MX_LIBRARY )` in the file project-root/CMakeLists.txt. This will set variables in CMake, `Matlab_FOUND`, `Matlab_EXECUTABLE` and `Matlab_ROOT_DIR`. For me this works and Matlab is recognized. If you see "No suitable Matlab and/or MX_Library version found" instead, it means that CMake failed to find Matlab. It's most probably not a problem with Gpufit.

The `Matlab_WORKING_DIRECTORY` variable is set by us and not important for building the Matlab binding (as explained in the second comment here). It can be ignored for this issue.

I would update CMake and try it again. If it still fails to detect Matlab, it might be good to contact CMake or try to manually tell CMake where Matlab is by setting the `Matlab_ROOT_DIR` variable and running CMake again ([find_package Matlab help](https://cmake.org/cmake/help/latest/module/FindMatlab.html) of CMake).

I will leave this open a bit and add it to the FAQ. If you want, try the things mentioned above and report if they worked for you.
