### ISSUE TITLE
How much faster/slower than GPU-LMFit is our GPUfit?

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#69]
- at comparable precision of the fitted parameters (and/or comparable number of iterations) on the same data and with the same model and estimator

And what ways do we have to automatically compare the performance of both?

The software is contained as supplementary software package to the publication

http://europepmc.org/articles/PMC3794933#pone.0076665.s001

Somewhat related is #42

**Comment by superchromix** [comment]
Not sure that I understand what you mean here.  Gpufit is tested against 
GPULMFit in the paper.... ?

**Comment by jkfindeisen** [comment]
Sorry, I forgot about this. I only have a printed version of the paper from before x-mas.

So I just have to look in the tests repository (https://github.com/adrianjp88/Tests) for a way how to use GPU-LMFit.

**Comment by jkfindeisen** [comment]
Mark produced kind of "final" versions of the figures and in there is a comparison between our GPUfit and GPU-LMFit (the 32 bit published version which also includes an initial parameters estimation). It seems our GPUfit is always faster but both libraries seem to approach a common speed for large number of fit points.
