### ISSUE TITLE
Example Help

### ISSUE THREAD

**Issue by soulslicer** [gpufit/Gpufit#70]
I have a problem statement that I need to solve. I have a Residual of [N*1] and a Jacobian of [N*P] where N is the number of residuals/losses and P is the number of parameters I want to estimate. I also have my P value [N*1]

How can I use your API for LM to solve for delta P or the updated P?

**Comment by jkfindeisen** [comment]
In general, you need to set up a suitable model. The model should be able to calculate function values and values of the derivatives for each data point. This must then be added in the form of CUDA code to the source base of Gpufit and this modified Gpufit must be built. If necessary, another estimator has to be created too (if the noise cannot be well described by Gaussian or Poissonian noise). The source code and the documentation should give some examples.

The number of residuals is probably also the number of data points.

**Comment by soulslicer** [comment]
Do you have an explanation provided for the example code somewhere? Eg. the math behind the problem. Right now I am using Pytorch's APIs to do Gauss Newton myself
