### ISSUE TITLE
LinearFit1D test fails with estimator MLE

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#70]
The output_state is "Maximum number of iterations exceeded" in case of the MLE estimator and that seems strange.

Either the test data is particularly singular or the MLE estimator is not working. We should find out what happens.

**Comment by jkfindeisen** [comment]
Sorry, I had not yet commited my changes to the test leading to it failing.

fbb473cebd65368079de4462869f5b5830a491f6

Please note, that I don't understand why it fails or why it should fail.

**Comment by adrianjp88** [comment]
The model curve values must be always positive. [mle.cuh](https://github.com/gpufit/GPUfit/blob/master/GPUfit/mle.cuh) is fixed and the mentioned test is updated.
