### ISSUE TITLE
Matlab Binding Estimators Example Help

### ISSUE THREAD

**Issue by willkim1** [gpufit/Gpufit#71]
Thank you for building this amazing package. I looked through the matlab binding examples and they are helpful when using model fits.

Is there an example you can add showing how would you use the estimators like LSE? I am trying to mirror the matlab function "lsqnonlin". Thank you.

**Comment by jkfindeisen** [comment]
You could use the Matlab examples and just substitute EstimatorID.MLE with EstimatorID.LSE and they would run through as well. That's all you have to do and you are ready to mirror lsqnonlin.
