### ISSUE TITLE
Failure building in linux on make command

### ISSUE THREAD

**Issue by jahdoos** [gpufit/Gpufit#72]
I am installing on linux with e5-4650 below are the gcc info, and the error trace. any suggestions? Thanks!

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)

[  5%] Building CXX object Cpufit/CMakeFiles/Cpufit.dir/lm_fit_cpp.cpp.o
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_derivatives_gauss2d(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:139:54: error: ‘sqrt’ is not a member of ‘std’
     std::size_t const  fit_size_x = std::size_t(std::sqrt(info_.n_points_));
                                                      ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:139:54: note: suggested alternative: ‘sort’
     std::size_t const  fit_size_x = std::size_t(std::sqrt(info_.n_points_));
                                                      ^~~~
                                                      sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:146:29: error: ‘exp’ was not declared in this scope
             REAL const ex = exp(-(argx + argy));
                             ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:146:29: note: suggested alternative: ‘ex’
             REAL const ex = exp(-(argx + argy));
                             ^~~
                             ex
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_derivatives_gauss2delliptic(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:167:54: error: ‘sqrt’ is not a member of ‘std’
     std::size_t const  fit_size_x = std::size_t(std::sqrt(info_.n_points_));
                                                      ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:167:54: note: suggested alternative: ‘sort’
     std::size_t const  fit_size_x = std::size_t(std::sqrt(info_.n_points_));
                                                      ^~~~
                                                      sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:174:29: error: ‘exp’ was not declared in this scope
             REAL const ex = exp(-(argx +argy));
                             ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:174:29: note: suggested alternative: ‘ex’
             REAL const ex = exp(-(argx +argy));
                             ^~~
                             ex
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_derivatives_gauss2drotated(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:194:54: error: ‘sqrt’ is not a member of ‘std’
     std::size_t const  fit_size_x = std::size_t(std::sqrt(info_.n_points_));
                                                      ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:194:54: note: suggested alternative: ‘sort’
     std::size_t const  fit_size_x = std::size_t(std::sqrt(info_.n_points_));
                                                      ^~~~
                                                      sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:202:26: error: ‘sin’ was not declared in this scope
     REAL const rot_sin = sin(parameters_[6]);
                          ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:202:26: note: suggested alternative: ‘stdin’
     REAL const rot_sin = sin(parameters_[6]);
                          ^~~
                          stdin
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:203:26: error: ‘cos’ was not declared in this scope
     REAL const rot_cos = cos(parameters_[6]);
                          ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:210:29: error: ‘exp’ was not declared in this scope
             REAL const ex = exp((-0.5f) * (((arga / sig_x) * (arga / sig_x)) + ((argb / sig_y) * (argb / sig_y))));
                             ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:210:29: note: suggested alternative: ‘ex’
             REAL const ex = exp((-0.5f) * (((arga / sig_x) * (arga / sig_x)) + ((argb / sig_y) * (argb / sig_y))));
                             ^~~
                             ex
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_derivatives_gauss1d(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:252:19: error: ‘exp’ was not declared in this scope
         REAL ex = exp(-argx);
                   ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:252:19: note: suggested alternative: ‘ex’
         REAL ex = exp(-argx);
                   ^~~
                   ex
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_derivatives_cauchy2delliptic(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:264:54: error: ‘sqrt’ is not a member of ‘std’
     std::size_t const  fit_size_x = std::size_t(std::sqrt(info_.n_points_));
                                                      ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:264:54: note: suggested alternative: ‘sort’
     std::size_t const  fit_size_x = std::size_t(std::sqrt(info_.n_points_));
                                                      ^~~~
                                                      sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_derivatives_fletcher_powell_helix(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:333:63: error: ‘sqrt’ is not a member of ‘std’
     derivatives[0 * info_.n_points_ + 1] = 10.f * p[0] / std::sqrt(arg);
                                                               ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:333:63: note: suggested alternative: ‘sort’
     derivatives[0 * info_.n_points_ + 1] = 10.f * p[0] / std::sqrt(arg);
                                                               ^~~~
                                                               sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:338:63: error: ‘sqrt’ is not a member of ‘std’
     derivatives[1 * info_.n_points_ + 1] = 10.f * p[1] / std::sqrt(arg);
                                                               ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:338:63: note: suggested alternative: ‘sort’
     derivatives[1 * info_.n_points_ + 1] = 10.f * p[1] / std::sqrt(arg);
                                                               ^~~~
                                                               sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_derivatives_brown_dennis(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:356:50: error: ‘exp’ is not a member of ‘std’
         REAL const arg1 = p[0] + p[1] * t - std::exp(t);
                                                  ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:357:46: error: ‘sin’ is not a member of ‘std’
         REAL const arg2 = p[2] + p[3] * std::sin(t) - std::cos(t);
                                              ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:357:46: note: suggested alternative: ‘min’
         REAL const arg2 = p[2] + p[3] * std::sin(t) - std::cos(t);
                                              ^~~
                                              min
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:357:60: error: ‘cos’ is not a member of ‘std’
         REAL const arg2 = p[2] + p[3] * std::sin(t) - std::cos(t);
                                                            ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:357:60: note: suggested alternative: ‘ios’
         REAL const arg2 = p[2] + p[3] * std::sin(t) - std::cos(t);
                                                            ^~~
                                                            ios
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:362:69: error: ‘sin’ is not a member of ‘std’
         derivatives[3 * info_.n_points_ + point_index] = 2.f * std::sin(t) * arg2;
                                                                     ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:362:69: note: suggested alternative: ‘min’
         derivatives[3 * info_.n_points_ + point_index] = 2.f * std::sin(t) * arg2;
                                                                     ^~~
                                                                     min
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_values_cauchy2delliptic(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:368:33: error: ‘sqrt’ is not a member of ‘std’
     int const size_x = int(std::sqrt(REAL(info_.n_points_)));
                                 ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:368:33: note: suggested alternative: ‘sort’
     int const size_x = int(std::sqrt(REAL(info_.n_points_)));
                                 ^~~~
                                 sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_values_gauss2d(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:389:33: error: ‘sqrt’ is not a member of ‘std’
     int const size_x = int(std::sqrt(REAL(info_.n_points_)));
                                 ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:389:33: note: suggested alternative: ‘sort’
     int const size_x = int(std::sqrt(REAL(info_.n_points_)));
                                 ^~~~
                                 sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:398:23: error: ‘exp’ was not declared in this scope
             REAL ex = exp(-(argx +argy));
                       ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:398:23: note: suggested alternative: ‘ex’
             REAL ex = exp(-(argx +argy));
                       ^~~
                       ex
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_values_gauss2delliptic(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:407:33: error: ‘sqrt’ is not a member of ‘std’
     int const size_x = int(std::sqrt(REAL(info_.n_points_)));
                                 ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:407:33: note: suggested alternative: ‘sort’
     int const size_x = int(std::sqrt(REAL(info_.n_points_)));
                                 ^~~~
                                 sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:415:23: error: ‘exp’ was not declared in this scope
             REAL ex = exp(-(argx + argy));
                       ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:415:23: note: suggested alternative: ‘ex’
             REAL ex = exp(-(argx + argy));
                       ^~~
                       ex
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_values_gauss2drotated(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:425:33: error: ‘sqrt’ is not a member of ‘std’
     int const size_x = int(std::sqrt(REAL(info_.n_points_)));
                                 ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:425:33: note: suggested alternative: ‘sort’
     int const size_x = int(std::sqrt(REAL(info_.n_points_)));
                                 ^~~~
                                 sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:434:20: error: ‘sin’ was not declared in this scope
     REAL rot_sin = sin(parameters_[6]);
                    ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:434:20: note: suggested alternative: ‘stdin’
     REAL rot_sin = sin(parameters_[6]);
                    ^~~
                    stdin
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:435:20: error: ‘cos’ was not declared in this scope
     REAL rot_cos = cos(parameters_[6]);
                    ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:447:19: error: ‘exp’ was not declared in this scope
                 = exp((-0.5f) * (((arga / sig_x) * (arga / sig_x)) + ((argb / sig_y) * (argb / sig_y))));
                   ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:447:19: note: suggested alternative: ‘ex’
                 = exp((-0.5f) * (((arga / sig_x) * (arga / sig_x)) + ((argb / sig_y) * (argb / sig_y))));
                   ^~~
                   ex
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_values_gauss1d(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:477:19: error: ‘exp’ was not declared in this scope
         REAL ex = exp(-argx);
                   ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:477:19: note: suggested alternative: ‘ex’
         REAL ex = exp(-argx);
                   ^~~
                   ex
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_values_fletcher_powell_helix(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:514:23: error: ‘atan’ was not declared in this scope
         theta = .5f * atan(p[1] / p[0]) / pi;
                       ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:514:23: note: suggested alternative: ‘data_’
         theta = .5f * atan(p[1] / p[0]) / pi;
                       ^~~~
                       data_
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:516:23: error: ‘atan’ was not declared in this scope
         theta = .5f * atan(p[1] / p[0]) / pi + .5f;
                       ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:516:23: note: suggested alternative: ‘data_’
         theta = .5f * atan(p[1] / p[0]) / pi + .5f;
                       ^~~~
                       data_
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:525:30: error: ‘sqrt’ is not a member of ‘std’
     values[1] = 10.f * (std::sqrt(p[0] * p[0] + p[1] * p[1]) - 1.f);
                              ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:525:30: note: suggested alternative: ‘sort’
     values[1] = 10.f * (std::sqrt(p[0] * p[0] + p[1] * p[1]) - 1.f);
                              ^~~~
                              sort
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_values_brown_dennis(std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:537:50: error: ‘exp’ is not a member of ‘std’
         REAL const arg1 = p[0] + p[1] * t - std::exp(t);
                                                  ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:538:46: error: ‘sin’ is not a member of ‘std’
         REAL const arg2 = p[2] + p[3] * std::sin(t) - std::cos(t);
                                              ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:538:46: note: suggested alternative: ‘min’
         REAL const arg2 = p[2] + p[3] * std::sin(t) - std::cos(t);
                                              ^~~
                                              min
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:538:60: error: ‘cos’ is not a member of ‘std’
         REAL const arg2 = p[2] + p[3] * std::sin(t) - std::cos(t);
                                                            ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:538:60: note: suggested alternative: ‘ios’
         REAL const arg2 = p[2] + p[3] * std::sin(t) - std::cos(t);
                                                            ^~~
                                                            ios
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::calc_chi_square(const std::vector<float>&)’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:719:65: error: ‘log’ is not a member of ‘std’
                     += 2 * (deviant - data_[pixel_index] * std::log(values[pixel_index] / data_[pixel_index]));
                                                                 ^~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::solve_equation_system_gj()’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:777:29: error: ‘fabs’ was not declared in this scope
                         if (fabs(alpha[jp*info_.n_parameters_to_fit_ + ip]) >= big)
                             ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:777:29: note: suggested alternative: ‘labs’
                         if (fabs(alpha[jp*info_.n_parameters_to_fit_ + ip]) >= big)
                             ^~~~
                             labs
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp: In member function ‘void LMFitCPP::modify_step_width()’:
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:893:42: error: ‘sqrt’ was not declared in this scope
     size_t const n_parameters = (size_t)(sqrt((REAL)(hessian_.size())));
                                          ^~~~
/home/kimchi/packages/Gpufit/Cpufit/lm_fit_cpp.cpp:893:42: note: suggested alternative: ‘qsort’
     size_t const n_parameters = (size_t)(sqrt((REAL)(hessian_.size())));
                                          ^~~~
                                          qsort
Cpufit/CMakeFiles/Cpufit.dir/build.make:101: recipe for target 'Cpufit/CMakeFiles/Cpufit.dir/lm_fit_cpp.cpp.o' failed
make[2]: *** [Cpufit/CMakeFiles/Cpufit.dir/lm_fit_cpp.cpp.o] Error 1
CMakeFiles/Makefile2:1048: recipe for target 'Cpufit/CMakeFiles/Cpufit.dir/all' failed
make[1]: *** [Cpufit/CMakeFiles/Cpufit.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by antoscha** [comment]
Just insert `#include <math.h>` after `#include "lm_fit.h"` in Cpufit/lm_fit_cpp.cpp

**Comment by jahdoos** [comment]
Thanks - this worked!

**Comment by jkfindeisen** [comment]
It is now also fixed in the repository in 0ec065830bdc448e448b6cc26042b77878e48ef7

`cmath` has been used instead of `math.h`, but it should not make a difference on most systems, I believe.
