### ISSUE TITLE
How to obtain Python wheel file? pyGpufit/dist/pyGpufit-X.Y.Z-py2.py3-none-any.whl

### ISSUE THREAD

**Issue by mikejhuang** [gpufit/Gpufit#75]
Hi, thank you very much for your great work with this code. I'm trying to install the python package. 
The main installation instructions say:

cd pyGpufit/dist
pip install pyGpufit-X.Y.Z-py2.py3-none-any.whl

The readme in the python directory says:
pip install --no-index --find-links=LocalPathToWheelFile pyGpufit

I can't find the .whl file. The pyGpufit/dist folder does not exist in the repository.

**Comment by jkfindeisen** [comment]
On Linux, after you execute `make`, the wheel file of the Python binding is located at `BUILD_DIRECTORY/pyGpufit/dist`. The main installation instruction assumed that you are currently at the build directory. Please search at this location. If there is no `pyGpufit/dist` folder in the build directory, check if `make` fails. It might be that the Python package could not be created for some reason.
