### ISSUE TITLE
Memory initialization errors 

### ISSUE THREAD

**Issue by delorytheape** [gpufit/Gpufit#76]
I get errors when running the cuda-memcheck tool checking for correct memory initialization. 
For example; I have successfully build and run the examples, but when I run
```
cuda-memcheck --tool initcheck ./Linear_Regression_Example
```
I get 10000 errors (one for each fit) complaining about an "uninitialized __global__ memory read of size 4", coming from line 1205 of Gpufit/Gpufit/cuda_kernels.cu 
It appears that the contents of the array n_iterations[fit_index] has not been initialized prior to being read by that line of code. I am not sufficiently familiar with the code to know where best to initialize this array (? perhaps GPUData::init, but this is called for each chunk of fits?), maybe prior to the __while__ loop in LMFit::run()?? , or perhaps in the Device_Array constructor in gpu_data.cuh ??, or somewhere else?

Details are
OS: Ubuntu 18.04
GCC: 7.4.0
cmake: 3.14.3
Boost: 1.65.1
CUDA: 10.1.105-1
Nvidia Driver: 418.56
GPU: GTX1080ti
Gpufit: 0ec0658... May 24 16:02:38 2019 +0200

I modified line 98 of /Gpufit/Gpufit/CMakeLists.txt to the following (pass additional debugging flags to the compiler);
```
    list( APPEND CUDA_NVCC_FLAGS --std=c++11;--ptxas-options=-v;-g;-G;-lineinfo;)
```

I used the following commands to build;
```
mkdir Gpufit-build
cd Gpufit-build
cmake -DCMAKE_BUILD_TYPE=DEBUG ../Gpufit
make 
```
I can successfully run the examples eg.
```
./Linear_Regression_Example
```
I then run the memory initialization test with  eg;
```
cuda-memcheck --tool initcheck ./Linear_Regression_Example
```
and get the errors.

**Comment by adrianjp88** [comment]
Thank you for finding and reporting this error so explicitly. You are right! The array n_iterations_ is used without being initialized. This is fixed in a17f2a7da2ec0056fcb9bdfdcb18ad506f9217ab by initializing the array in `GPUData::init`. It is true that this function is called for every chunk of fits. The size of n_iterations_ is equal the number of fits per chunk and needs to be reinitialized for every chunk.
