### ISSUE TITLE
Adding too many models causes "too many resources requested for launch" error

### ISSUE THREAD

**Issue by ironictoo** [gpufit/Gpufit#77]
I have been steadily adding models to a fork of Gpufit. Things were going well but when I hit a certain number (it varies but around 13 total models, including the 8 included models) I start getting an error "Error in gpufit: too many resources requested for launch". The puzzling thing is this error can be triggered running the unmodified executable "Gpufit_Cpufit_Performance_Comparison", which of course will not use any of the added models. Including the new models in the switch statement in "models.cuh" is enough to trigger this error, even if they are never utilized. Also the number of fits needs to be above a certain amount (I get it at 100,000 fits in "Gpufit_Cpufit_Performance_Comparison").

Any idea what might be going on? From what I've read the three possibilities are:
* Too large a block or grid size.
* Too many registers
* Too much shared memory
In this case the closest fit is maybe "too many registers"? Are registers reserved for each model, putting an effective upper limit on the number of models that can be in use? Something else?

I am running this under Ubuntu 18.04, CUDA driver 10.1. The core Gpufit files are unmodified (some very minor edits to the CMake file to get CUBLAS to work under linux), except for adding the new models. I am using CUBLAS (but this error is triggered with and without CUBLAS).

**Comment by adrianjp88** [comment]
Hi,
thank you for reporting this error. Your assumption about the registers is right. Adding model functions to `models.cuh` can increase the number of registers per thread used by the kernel `cuda_calc_curve_values()`. If the number of registers used by a kernel exceeds the available number of registers per thread block for a certain [compute capability](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities) the error '_too many resources requested for launch_' occurs.

The commit aa468b45003564fd6be780116e71e8136eb30085 limits the number of threads per block and extends in this way the space for adding model functions to Gpufit.

Decreasing the number of threads per block to 256 doesn't affect the performance, but adding many model functions might have a slight impact on the computation speed. To work around this problem comment out unused models in function `calculate_model()` in file [model_cuh](https://github.com/gpufit/Gpufit/blob/master/Gpufit/models/models.cuh).

**Comment by ironictoo** [comment]
Perfect, works great now with all 9 models we have added so far. Thanks.
