### ISSUE TITLE
binary package and python OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by vzickus** [gpufit/Gpufit#79]
On Windows 10, using Gpufit_1.1.0_win64_cublas_build201804131033 binary: pip happily installs pyGpufit-1.1.0-py2.py3-none-win_amd64.whl, however, importing pygpufit gives the following:

```
import pygpufit.gpufit as gf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygpufit\gpufit.py", line 24, in <module>
    lib = cdll.LoadLibrary(lib_path)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Searching online it seems like a .dll issue, but which dll do I actually need (is it something worth adding to the documentation, or is this supposed to be common knowledge)?

**Comment by apriori** [comment]
Did you happen to find a solution? I tried to find determine the dll dependencies. Nothing really striking there.

**Comment by apriori** [comment]
I had to add the path to the dlls to my system PATH variable. This is weird and should actually not be needed. Anyway, things are working now.
