### ISSUE TITLE
Matlab gpufit_constrained wrong input check

### ISSUE THREAD

**Issue by AlanMiranda** [gpufit/Gpufit#83]
I noticed that the inputs check in the matlab function "gpufit_constrained" is incorrect. When user_info is supplied, it is ignored because the condition "if nargin < 12" should be "if nargin < 11" in order to not initialize the user_info with an empty array. The rest of the nargin checks need to be corrected as well by substracting one to the nargin value check. After these corrections the function works correctly.

**Comment by jkfindeisen** [comment]
You're right. I fixed it in the last commit.
