### ISSUE TITLE
Python errors when packaging read-only files

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#83]
Happens with the runtime ("Access is denied error") when including it in the wheel creation. Needs to be fixed one way or the other.

If nothing else works we can copy the runtime somewhere and manually remove the read-only flags. Then it works.

**Comment by bjoernthiel** [comment]
fixed

**Comment by jkfindeisen** [comment]
The fix in 16859d3f1a9151548b68d36499553823901f5b39 appears from nowhere. I would have preferred a small comment explaining the necessity. I will add it.

**Comment by jkfindeisen** [comment]
Also we now statically link to the VC runtime, since ctypes anyway has problems otherwise.  See also #85
