### ISSUE TITLE
time.clock() in gpufit.py line 175 is deprecated in python3.8

### ISSUE THREAD

**Issue by sheldonxxd** [gpufit/Gpufit#84]
this error caused picasso gui crashed, please use time.process_time() instead to make it compatible for python 3.8.

### The crash info

![图片](https://user-images.githubusercontent.com/42539486/96072912-eb196680-0ed7-11eb-87ac-a526b4dc3ce1.png)

### Modification on gpufit.py

![图片](https://user-images.githubusercontent.com/42539486/96073082-44819580-0ed8-11eb-95d3-9f4f4bbcb8ee.png)

**Comment by jkfindeisen** [comment]
Thanks for the report. I replaced time.clock with [time.perf_counter](https://docs.python.org/3/library/time.html#time.perf_counter), which exists since Python 3.3.
