### ISSUE TITLE
Python with ctypes doesn't find the runtime in the package folder.

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#85]
And complains about it. See https://github.com/gpufit/GPUfit/issues/75#issuecomment-279726662. We either need:

- teach Python to find them there
- put them somewhere else where Python can find them
- install the runtime separately, if needed
- not use ctypes but something like swig (works in specpy which uses swig)

**Comment by jkfindeisen** [comment]
We will statically link to the VC runtime.

See also: https://cmake.org/Wiki/CMake_FAQ#How_can_I_build_my_MSVC_application_with_a_static_runtime.3F

**Comment by bjoernthiel** [comment]
linking runtime statically now

**Comment by jkfindeisen** [comment]
FYI The problem is known but not solved in the case of dynamic dependencies. See for example:

http://stackoverflow.com/questions/10755882/ctypes-wont-load-library
http://stackoverflow.com/questions/7586504/python-accessing-dll-using-ctypes
