### ISSUE TITLE
Handling batches of unequal-length data?

### ISSUE THREAD

**Issue by persimmon2500** [gpufit/Gpufit#85]
I want to do multiple curve-fittings in parallel. Conveniently, `gpufit` is optimized for fitting multiple curves in parallel. However, each of my curve-fittings is on a different number of points.

For instance, if I want to do 2 curve-fittings (`n_fits=2`), one of the fits has `n_points=400` and the other has `n_points=500`.

I am hoping that, for the `n_points=400` curve, I can "pad" it with zeros or null-values of some sort to make it length-500. Is there a way to do this so that `gpufit` will ignore the padding?

**Comment by superchromix** [comment]
I would suggest setting the "weights" value to 0 for the data points in the padding region?  In this situation, those data will not contribute to the chi-square value.
