### ISSUE TITLE
Expose all models in the Python API

### ISSUE THREAD

**Issue by lmmx** [gpufit/Gpufit#88]
I've just noticed that not all of the model IDs specified in the `constants.h` enum are likewise in the Python `ModelID` enum, and as a result can't be called through the standard interface by name.

0 to 12 in `constants.h`:

https://github.com/gpufit/Gpufit/blob/ab1c884d91a1100814a06feb3b983984bbcdee91/Gpufit/constants.h#L6-L20

0 to 5 in `gpufit.py`:

https://github.com/gpufit/Gpufit/blob/b1d09fd86ce077a8e87fb272aa348702ced25031/Gpufit/python/pygpufit/gpufit.py#L47-L54

- The [matlab interface](https://github.com/gpufit/Gpufit/blob/ab1c884d91a1100814a06feb3b983984bbcdee91/Gpufit/matlab/ModelID.m) has them all

Happy to submit a PR for this!

P.S - I just noticed these functions [are documented](https://github.com/gpufit/Gpufit/blob/ab1c884d91a1100814a06feb3b983984bbcdee91/docs/fit_model_functions.rst) but the docs haven't been put up on [the Read The Docs site](https://gpufit.readthedocs.io/en/latest/fit_model_functions.html)

**Comment by jkfindeisen** [comment]
Thanks for the observation. I added the Model Ids.
