### ISSUE TITLE
Sizes of input values passed to the interface needs to be checked

### ISSUE THREAD

**Issue by adrianjp88** [gpufit/GPUfit#9]
Data types of intern variables and interface arguments need to be set to meaningful types. Also, the sizes of input values passed to the interface need to be checked to ensure that operations performed on them do not lead to overflows.

**Comment by jkfindeisen** [comment]
if the data types change (for example to size_t for sizes) this has also to be done in the python & matlab bindings

**Comment by adrianjp88** [comment]
Data type of the interface argument n_fits changed from int to size_t. Also, pointers representing only one number are passed by value. The Matlab binding is already updated to this changes. Python needs to be updated.

Threre are still two internal unchecked type conversions that should be avoided and input values need to be checked.

**Comment by jkfindeisen** [comment]
Yes, Python needs to be updated. Where are the two internal unchecked type conversions that should be avoided? How can we check input values?

**Comment by jkfindeisen** [comment]
We agreed to have n_points also have size_t

**Comment by superchromix** [comment]
user info size is now type size_t.  it should be possible for user info size to be larger than a 32 bit number.

**Comment by jkfindeisen** [comment]
The types of the length parameters in the interface are not size_t. This solves this issue.

**Comment by bjoernthiel** [comment]
Renaming this issue (several times) resulted in forgetting about sentence two of the initial comment. 
That has not been fixed yet!

**Comment by jkfindeisen** [comment]
The problem is a bit, that we put multiple issues in one. They should be separated from the beginning on.
I therefore rename the issue to reflect the remaining content.

**Comment by jkfindeisen** [comment]
Remaining issue: ...**sizes of input values passed to the interface need to be checked to ensure that operations performed on them do not lead to overflows.**

**Comment by adrianjp88** [comment]
solved
