### ISSUE TITLE
cublas name should be changed

### ISSUE THREAD

**Issue by xiecookie** [gpufit/Gpufit#91]
![image](https://user-images.githubusercontent.com/28053553/125943417-91ca7a65-b5b7-442b-aec1-054aee6a4491.png)
line193 CMakeList.txt in Gpufit.
I use cuda11.1 and the cublas name is cublas_11 instead of cublas111 which causes a compile error in visual studio.
So I think cublas name should be changed.

**Comment by jkfindeisen** [comment]
See also #74

**Comment by jkfindeisen** [comment]
For Windows, this is now fixed (ed273cac245d0cfb64efe5f475942790adcda969).
