### ISSUE TITLE
CMake CUDA architecture flags should add PTX for All

### ISSUE THREAD

**Issue by jkfindeisen** [gpufit/GPUfit#99]
"Auto" is okay, but "All" does never add PTX, therefore not having future-compatibility

**Comment by jkfindeisen** [comment]
This will likely also fix #87.

**Comment by bjoernthiel** [comment]
done

**Comment by jkfindeisen** [comment]
Now CMake returns "-gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_20,code=sm_21;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_32,code=sm_32;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_52,code=compute_52" for CUDA 7.5 and "All".

Why is there no arch=compute_52,code=sm_52?

**Comment by bjoernthiel** [comment]
another CMake bug (unfortunately)

**Comment by jkfindeisen** [comment]
That wasn't the problem. The problem was the wrong "code=compute_52" instead of "code=compute_53". With 27f0d3123d84197160a330464c8821f6a611666d it's fixed. I'll add some comments explaining that "All" does not contain the latest PTX although in my opinion "All" should actually contain it or there should be an option like "All+PTX".

**Comment by bjoernthiel** [comment]
'All' now includes the latest PTX
